### ISSUE TITLE
Create the schemaResource constant

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#11543]
### User Story
As a RS developer, I want access to the resource initially passed into the file. 

### Description/Use Case
In `FhirToHl7Converter`, we would set a constant called `schemaResource` to 
equal the resource being passed into the file. That way, there would automatically be access in each file to the schema 
resource. It could then be used like so:
```
# resource: <Path to organization>
- name: performing-organization-name-pracrole
  condition: '%{schemaResource} is PractitionerRole'
  resource: '%resource.performer.resolve().organization.resolve()'
  schema: ./datatype/xon-organization
  constants:
    hl7OrgField: '%{hl7OBXField}-23'
```

See prime-router/docs/design/design/schema-resource-design.md for the full proposal.

### Acceptance Criteria
- [x] The initial resource can be accessed through a constant automatically added in the code rather than being defined in a file.
