### ISSUE TITLE
Modify prime-router/metadata/fhir_transforms/senders/default-sender-transform.yml to utilize observation-mapping table

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#11950]
As a ReportStream engineer, I want to modify our default sender transform so that all inbound messages utilize the observation-mapping table to identify reportable conditions from the LOINC/SNOMED codes in the observation resource

**Background Information**
Reportable condition information will be most useful and easy to work with if it exists in the FHIR bundle itself. Making use of the fact that FHIR allows for metadata about a resource to include tags that include a code and display value we can provide a tag to each observation resource in a FHIR bundle that describes the condition associated with that observation

Example:
```json
        {
            "fullUrl": "Observation/d683b42a-bf50-45e8-9fce-6c0531994f09",
            "resource": {
                "resourceType": "Observation",
                "id": "d683b42a-bf50-45e8-9fce-6c0531994f09",
                "status": "final",
                "code": {
                    "coding": [
                        {
                            "system": "http://loinc.org",
                            "code": "80382-5"
                        }
                    ],
                    "text": "Influenza virus A Ag [Presence] in Upper respiratory specimen by Rapid immunoassay"
                },
                "subject": {
                    "reference": "Patient/9473889b-b2b9-45ac-a8d8-191f27132912"
                },
                "performer": [
                    {
                        "reference": "Organization/1a0139b9-fc23-450b-9b6c-cd081e5cea9d"
                    }
                ],
                "valueCodeableConcept": {
                    "coding": [
                        {
                            "system": "http://snomed.info/sct",
                            "code": "260373001",
                            "display": "Detected"
                        }
                    ]
                },
                "meta": {
                    "tag": [
                          {
                              "code": "541000000000000",
                              "display": "Infection caused by novel Influenza A virus variant (disorder)"
                         }
                    ]
                }
            }
        }
```

In order to account for both HL7 and FHIR input from senders, the lookup should occur after conversion of the incoming HL7 V2 message into a FHIR bundle. Since the sender transforms are used after conversion from HL7 to FHIR, adding the below elements to the default sender transform will add the condition tag to the observation resource. The key that will be used is  the test ordered/test performed code value and the returned value will be the associated condition code mappedin the observation-mapping table.

```yaml
  - name: test-condition
    resource: 'Bundle.entry.resource.ofType(Observation)'
    condition: '%resource.code.coding.exists()'
    bundleProperty: '%resource.meta.tag.code'
    value: ['%resource.code.coding.code']
    valueSet:
      lookupTable:
        tableName: Observation-Mapping
        keyColumn: code
        valueColumn: condition_code
```
This element will check against the RCTC values loaded into the Observation-Mapping table.

Not all reportable conditions can be identified from order and result LOINC codes. In the case of bacterial cultures the condition is identified by the found organism which is populated in the result field/resource (OBX-5 or Bundle.entry.resource.ofType(Observation).value.valueCodeableConcept). In order to correctly tag these messages, an additional element will need to be added to the transform like below to check the result code.

```yaml
- name: result-condition
  resource: 'Bundle.entry.resource.ofType(Observation)'
  condition: '%resource.code.coding.exists() and %resource.meta.tag.code.not.exists()'
  bundleProperty: '%resource.meta.tag.code'
  value: ['%resource.valueCodeableConcept.coding.code']
  valueSet:
    lookupTable:
      tableName: Observation-Mapping
      keyColumn: code
      valueColumn: condition_code
```
This element should be placed after the above element as we only want to check the mapping for a result value if we have failed to find a match in the test ordered and test performed locations. 

*Additional Info**
Reference ticket#
