### ISSUE TITLE
Dependabot does not have access to frontend E2E test credentials

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-reportstream#13433]
## Problem statement

Dependabot is unable to complete the frontend build because E2E testing require credentials. This probably should be addressed by moving the credentials to Key Vault and retrieving them at run time.

## What you need to know
Dependabot frontend build error:
```
E2E tests
  TypeError: Missing username for login type: admin
      at map (file:///home/runner/work/prime-reportstream/prime-reportstream/frontend-react/playwright.config.ts:33:23)
      at Array.map (<anonymous>)
      at createLogins (file:///home/runner/work/prime-reportstream/prime-reportstream/frontend-react/playwright.config.ts:26:20)
      at file:///home/runner/work/prime-reportstream/prime-reportstream/frontend-react/playwright.config.ts:51:16
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
  Error: Process completed with exit code 1.
```

Dependabot PR vars:
```
Run ./.github/actions/build-frontend
  with:
    env-name: staging
    version: v-pre-release
    GITHUB_TOKEN: ***
```

Normal user PR vars:
```
Run ./.github/actions/build-frontend
  with:
    env-name: staging
    appinsights-staging-key: ***
    appinsights-prod-key: ***
    version: v-pre-release
    GITHUB_TOKEN: ***
    test-admin-user: ***
    test-admin-password: ***
    test-sender-user: ***
    test-sender-password: ***
    test-receiver-user: ***
    test-receiver-password: ***
```

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...
