### ISSUE TITLE
Update the NIST ELR mappings to use the correct spec for the *_ELR types

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14124]
### User Story
As a sender of NIST ELR HL7 messages, I would like the ELR specific datatypes to get translated

### Description/Use Case
Currently, when we read message into the NIST ELR Java class, the mappings do not work as they need to reference the *_ELR types

### Dev Notes
In `XPN_ELR/HumanName`, the mapping is currently
```
family:
  type: STRING
  valueOf: XPN.1.1
  expressionType: HL7Spec
```

when it needs to be

```
family:
  type: STRING
  valueOf: XPN_ELR.1.1
  expressionType: HL7Spec
```

### Acceptance Criteria
- [ ] All of the ELR datatypes are updated to reference the correct spec
- [ ] HL7Reader.kt updated (see comment referencing ticket)
