### ISSUE TITLE
FHIR->FHIR transforms can create a circular JSON structure which cannot be encoded to a string

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14257]
### User Story
As a report stream authorer of FHIR transforms, I would like to be guaranteed that the outputted FHIR bundle is always encodable.

### Description/Use Case
Discovered this while trying to write FHIR converter integration tests that use a sender transform.  If applied to a FHIR bundle created from a converted HL7 message
```yaml
  - name: sr-diagnostic-report-effective-date-time
    resource: '%diagnosticReport.effective'
    bundleProperty: '%resource.extension("https://reportstream.cdc.gov/fhir/StructureDefinition/hl7v2-date-time").value[x]'
    value: [ '%diagnosticReport.effective' ]
```
creates a circular structure in the FHIR bundle and the bundle cannot be encoded.

### Dev Notes
The work here should involve at a minimum diagnosing why it happens and fixing the transform as well as any other ones that might suffer from the same flaw.  If there is an easy to fix to the root issue it can get fixed, otherwise open up a new ticket

### Acceptance Criteria
- [x] The simple report transform can get applied to a converted HL7 message
- [x] (Optional) the root flaw in the transform code is fixed so that no transform can create a cirucle
