### ISSUE TITLE
resourceIndex is failing to evaluate properly in a FHIRPath expression

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#14924]
## Describe the bug
The FHIRTransform.setBundleProperty is not able to handle indexes passed into a schema via a resourceIndex. 

## Impact on ReportStream
We need to convert Observation to ServiceRequest.note according to the RADxMARS specification. When there are multiple Observation resources each one needs to be added as a separate note on ServiceRequest. That currently doesn't work and thus we are out of compliance with the specification.

## Steps to reproduce
1. add this schema file as `resources/metadata/fhir_transforms/receivers/obx-note.yml`
```
- elements:
  - name: obx-note
    resource: 'Bundle.entry.resource.ofType(ServiceRequest).note[%observationIndex]'
    bundleProperty: '%resource.text'
    value: [ '"test note"' ]
```
2. Add this element to `simple-report-sender-transform.yml`. Sub out your absolute path to `obx-note.yml`
```
  - name: sr-observation
    resource: Bundle.entry.resource.ofType(Observation)
    resourceIndex: observationIndex
    schema: file:ABSOLUTE/PATH/TO/obx-note.yml
```
3. Submit this file via postman or curl: [SR-test.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3381f68a13a5eb305c92d8dc43943c63aa57552d/SR-test.txt)
  - Can provide a postman collection if needed but zenhub doesn't allow JSON uploads. So feel free to ask.
 
4. Review that output does not have ServiceRequest.note populated. 

## Expected behavior
- [ ] There should be an equal number of ServiceRequest.note as there are Observation resources
- [ ] Each ServiceRequest.note.text should be populated with "test note".

## Additional context
I confirmed that the `observationIndex` is added to the list of constants passed to the fhirpath evaluator.

**Comment by mkalish** [comment]
FYI @brick-green @arnejduranovic @Andrey-Glazkv @brandonnava 
Two notes:

- The test schema is a little off.  I think it would actually be 
```
elements:
  - name: obx-note
    resource: 'Bundle.entry.resource.ofType(ServiceRequest)'
    bundleProperty: '%resource.note[%observationIndex].text'
    value: [ '"test note"' ]
```
since we need to add a new note. 
- I'm going to convert this to a story rather than a bug as this is not something that has ever been supported via FHIR->FHIR transforms.   We actually [specifically log an error](https://github.com/CDCgov/prime-reportstream/pull/8652/files#diff-b726355f499836c39bb55066c3ddb947608412e06de81be2b9c81cd8058a34a1R178) when trying to use an expression with a constant in it.  I don't see why it shouldn't be possible to update the code to support this, but this is a new feature.
