### ISSUE TITLE
Update the HL7 converter library to support conditions at the message level

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#15511]
### User Story
As a mapping implementor, I would like to be able to specify a condition for adding a resource at the top level of a mapping definition.

### Description/Use Case
Currently, our mapping for a HL7 message cannot have any conditions added, but they will be required to implement the ADT_* mappings.  For example, we will only create a CareTeam FHIR resource if ROL-3.1 is "PP"

### Dev Notes
The goal is to support something like this

```yml
  - resourceName: Provenance
    segment: MSH
    condition: MSH.1 NOT_NULL
    resourcePath: segments/MSH/Provenance-Transformation
```

_Top level mapping definition are the various message types like ORU_R01.yml, ADT_01.yml etc._

### Acceptance Criteria
- [ ] The HL7 converter library supports conditions add the top of the mapping definition
