### ISSUE TITLE
Convert unwanted conditions to notes in a FHIR to HL7 transform for MARS OTC data

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15584]
## Problem statement
Platform has identified that an accurate conversion of unwanted conditions to notes is not possible with a FHIR-to-FHIR transform. Therefore, Engagement team should use a FHIR to HL7 transform to complete this task for the near future.

## What you need to know

https://app.zenhub.com/workspaces/engagement-6166edbd409257001e09f1b2/issues/gh/cdcgov/prime-reportstream/14693

- In a FHIR to HL7 receiver transform filter out Observations from being mapped to OBX segments
- Example:
```
  # Override observation-result-with-aoe from base mappints to map only reportable conditions following condition_code (see: observation-mapping.csv for more detail)
  # RSV:  	55735004, COVID:	840539006
  - name: observation-result-with-aoe
    resource:         
        - "(%resource.code.coding.extension('https://reportstream.cdc.gov/fhir/StructureDefinition/condition-code').value.where(code  in ('55735004'|'840539006')).exists())"
     

  # Map unwanted conditions to notes
  # RSV:  	55735004, COVID:	840539006
  # Create schema that takes unwanted conditions and maps them to notes
  - name: unwated-conditions-to-notes
    resource:         
        - "(%resource.code.coding.extension('https://reportstream.cdc.gov/fhir/StructureDefinition/condition-code').value.where(code  in ('55735004'|'840539006')).exists().not())"
        - schema: unwanted-conditions-to-notes.yml
```
## Acceptance criteria

- [x] FHIR-to-HL7 transform created for OTC data in MARS format that converts unwanted conditions to notes.

## To do

- [ ] ...
