### ISSUE TITLE
yml file validation not allowing boolean value in condition for transforms

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#15622]
In order to override base mappings in a receiver transform, it is possible to change the condition value to boolean "false" which prevents the mapping of the related fhir element to hl7 fields. i.e. 

base mappings:

```yml
  - name: obx-equipment-instance-identifier
    resource: '%resource.device.resolve().identifier.union(%resource.extension(%`rsext-obx-observation`).extension.where(url = "OBX.18").tail().value.resolve().identifier)'
    condition: '%resource.value.exists() or %resource.extension(%`rsext-assigning-authority`).exists()'
    schema: classpath:/metadata/hl7_mapping/datatypes/identifier-extension/EI.yml
    resourceIndex: equipmentInstanceIdentifierIndex
    constants:
      eiFieldPath: '%{hl7OBXField}-18(%{equipmentInstanceIdentifierIndex})'
```

transform override:

```yml
    # removes equipment instance identifier from OBX-18-1, OBX-18-2, OBX-18-3, OBX-18-4
  - name: obx-equipment-instance-identifier
    condition: false
```

The current .yml validation does not allow a boolean value in the condition parameter and  expects only a string (see screenshot). Can this be amended to allow boolean values as well as strings in transforms.

<img width="869" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76812b33eded3378721cf0954ce579580b198f38/yaml-file-validation-bug.png" alt="yaml-file-validation-bug.png" />
