### ISSUE TITLE
Importing JosiahSiegel GHA: AzViz-action@v1.0.4

### ISSUE THREAD

**Issue by emvaldes** [CDCgov/prime-reportstream#16156]
**Profile**: **[JosiahSiegel](https://github.com/JosiahSiegel)**
**Status**: Importing (Product Backlog)

**Objective**: Azure Visualizer aka 'AzViz' - PowerShell module to automatically generate Azure resource topology diagrams by just typing a PowerShell cmdlet and passing the name of one or more Azure Resource Group(s).
**Note**: Cloud admins are not anymore doomed to manually document a cloud environment!
The pain of inheriting an undocumented cloud landscape to support is gone.
**It is capable of**:
- Finding Resources in a Azure Resource Group and identifying their dependencies.
- Plot nodes and edges to represent Azure Resources and their dependencies on a graph.
- Insert appropriate Azure Icons on basis of resource category/sub-category.
- Label each resource with information like Name, Category, Type etc.
- Generate visualization in formats like: .png and .svg
- Output image can be in 'light', 'dark' or 'neon' theme.
- Can target more than one resource group at once.
- Change direction in which resource groups are plotted, i.e, left-to-right or top-to-bottom.

**Target**: [AzViz-action@v1.0.4 : 663e242](https://github.com/JosiahSiegel/AzViz-action/tree/663e24299a6336f1ff8dbddadfac1ba5d462f731)
**Latest**: [AzViz-action](https://github.com/JosiahSiegel/AzViz-action) (`0ae465075a8f0401db5256f1ea35193ee08ec687`)

**Warning**: This is a clone to another repository [PrateekKumarSingh/AzViz](https://github.com/PrateekKumarSingh/AzViz)

The `AzViz-action` is a GitHub Action designed to automate the generation of Azure resource topology diagrams directly within your CI/CD pipelines. It leverages the [AzViz PowerShell module](https://github.com/PrateekKumarSingh/AzViz) to visualize Azure resources, aiding in documentation and infrastructure management.

**Key Features:**

- **Automated Visualization:** Generates diagrams of Azure resources, providing insights into resource configurations and relationships.
- **Customization Options:** Offers parameters to tailor the visualization, including themes, depth of resource categories, verbosity, and output formats.
- **Integration with Azure Login:** Requires authentication via the `azure/login` action to access Azure resources securely.

**Inputs:**

- `resource-group` (required): Comma-separated list of Azure resource groups to visualize.
- `out-file` (required): Path where the generated graph will be saved; defaults to `output/viz.svg`.
- `sub-name` (required): Azure subscription name; defaults to `Pay-As-You-Go`.
- `theme` (optional): Graph theme (`dark`, `light`, `neon`); defaults to `neon`.
- `depth` (optional): Level of Azure resource sub-categories to include in the visualization (`1` or `2`); defaults to `1`.
- `verbosity` (optional): Level of information to include in the visualization (`1` or `2`); defaults to `1`.
- `format` (optional): Graph format (`png` or `svg`); defaults to `svg`.
- `direction` (optional): Direction in which resource groups are plotted (`left-to-right` or `top-to-bottom`); defaults to `top-to-bottom`.
- `exclude-types` (optional): Exclude resources via string search; defaults to `'*excludethisthing1,excludethisthing2*'`.
- `splines` (optional): Controls how edges appear in the visualization (`spline`, `polyline`, `curved`, `ortho`, `line`); defaults to `spline`.

**Technical Evaluation:**

The action is implemented as a composite action, executing a PowerShell script (`viz_run.ps1`) to perform the visualization tasks. The workflow includes the following steps:

1. **Graphviz Installation:** Installs Graphviz, a prerequisite for AzViz, using package managers appropriate for the runner's operating system.
2. **AzViz Module Installation:** Installs and imports the AzViz PowerShell module.
3. **Azure Authentication:** Requires prior authentication using the `azure/login` action with `enable-AzPSSession: true` to establish a session with Azure.
4. **Visualization Execution:** Runs the `viz_run.ps1` script with the provided inputs to generate the topology diagram.

**Usage Example:**

```yaml
jobs:
  generate-viz:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}
          enable-AzPSSession: true
      - name: Generate Azure Resource Topology Diagram
        uses: JosiahSiegel/AzViz-action@v1.0.3
        with:
          resource-group: 'myResourceGroup'
          out-file: 'output/viz.svg'
          sub-name: 'MySubscription'
      - name: Upload Diagram
        uses: actions/upload-artifact@v2
        with:
          name: viz
          path: output/*
```

**Relevance to Your Pipeline:**

If your pipeline involves managing Azure resources and you require automated, up-to-date visualizations of your infrastructure, the `AzViz-action` provides significant value. It facilitates better understanding and documentation of resource configurations and relationships. However, if your workflow does not involve Azure resources or if such visualizations are not necessary, this action may be considered non-essential.

**Conclusion:**

The `AzViz-action` offers a streamlined solution for generating Azure resource topology diagrams within GitHub workflows. Its utility depends on your pipeline's specific requirements for infrastructure visualization and documentation. Assessing your current processes for managing and documenting Azure resources will help determine the action's relevance to your workflows.
