### ISSUE TITLE
Housekeeping connect-ovpn GitHub Action pending files

### ISSUE THREAD

**Issue by emvaldes** [CDCgov/prime-reportstream#16484]
I had initially intended to change the **.github/actions/connect-ovpn/** inputs configuration FILE_OVPN to point at the **.github/vpn/** folder where all the *.ovpn files reside. I have to also remove the **example.ovpn** file to avoid confusion and others using it as a reference.

``` yaml
...
inputs:
...
  FILE_OVPN:
    description: 'Location file open vpn'
    required: true
    default: './config.ovpn' -> '.github/vpn/config.ovpn'
...
```

``` console
$ git status ;
On branch devsecops/emv/cleanup-connect-ovpn
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   actions/connect-ovpn/config.ovpn

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    actions/connect-ovpn/example.ovpn
	deleted:    vpn/config.ovpn
```

This is something I need to correct because files in that folder are environment specific and this is application specific. There is no need to alter the default connect-ovpn configuration file.
