### ISSUE TITLE
Investigate and design OBX.33 mapping strategy

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#16522]
### User Story
As a RS engineer, I want to ensure all FHIR mappings are completed so that they are maintainable and concise.

### Description/Use Case
The FHIR inventory specifies that `OBX.33` is to be mapped to `Observation.specimen` as a reference. Determine whether we will support this mapping or continue to support it only as an HL7 > FHIR > HL7 extension in OBXExtension. If we will support this mapping, update the mappings accordingly.

### Risks/Impacts/Considerations
The FHIR bundles in the SR sample files have this reference populated, which has the result of `OBX.33` being populated when it was not intended to do so at the time. We should coordinate with SimpleReport to determine if this value is populated in production data and if UP HL7 receivers would be able to support this value if sent to them.

### Dev Notes
This is the FHIR > HL7 mapping in Observation/OBX that was intended to be tested by the `test correctly handles OBX-33 without extension` test in the OBX to Observation integration test suite:

```
  # the specimen field in FHIR does not repeat so an extension is needed to capture additional specimen identifiers
  # as such, use the extension when it is populated
  - name: obx-related-specimen-identifier
    resource: '%resource.specimen.resolve().identifier.where(extension(%`rsext-hl7v2Component`).value = "SPM.2.1")'
    condition: '%resource.extension.where(url = "OBX.33").exists().not()'
    constants:
      eipFieldPath: '%{hl7OBXField}-33'
    schema: classpath:/metadata/hl7_mapping/datatypes/identifier-placerAssignedIdentifier/EIP.yml

  - name: obx-related-specimen-identifier-backup
    resource: '%resource.specimen.resolve().identifier.where(extension(%`rsext-hl7v2Component`).value = "SPM.2.2")'
    condition: >
      %resource.specimen.resolve().identifier.where(extension(%`rsext-hl7v2Component`).value = "SPM.2.1").exists().not() and
      %resource.extension.where(url = "OBX.33").exists().not()
    constants:
      eipFieldPath: '%{hl7OBXField}-33'
    schema: classpath:/metadata/hl7_mapping/datatypes/identifier-fillerAssignedIdentifier/EIP.yml
```

### Acceptance Criteria
- Determine if OBX.33 as defined in the FHIR inventory will be a supported mapping.
- If we will support the mapping, implement the mapping.
