### ISSUE TITLE
Carbon Health Onboarding – Test with Delaware (DE)

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16696]
## Steps for testing Carbon Health with new receiver
- [x] In staging, add Carbon Health as approved sender to Routing Filter
- [x] Check if receiver has any specific testing requirements including:
  - [ ] Patient Name restrictions
  - [ ] Receiver Portal access requirements
  - [ ] Check if Convert Date/Time to local receiver timezone is activated
- [x] Inform Carbon Health to send test messages to receiver per receiver requirements
- [x] Ensure messages get sent to that receiver
  - [ ] (if necessary) Update receiver quality filters
- [x] Notify receiver to approve test message (provide MessageID, Patient Name, Filename)
- [x] (if necessary) Make changes per receiver requirements

## Acceptance Criteria 
- [x] Receiver can successfully receive test messages and has approved them
- [x] Move to production pending approval of test messages from STLT

**Comment by victor-chaparro** [comment]
Delaware requested this transform to the messages coming from Carbon Health MSH-4 = Carbon Health^05D2121942^CLIA
Add this transform to `DE-receiver-transform.yml`
```
  - name: sending-facility_namespace-id
    value:
     - 'Bundle.entry.resource.ofType(MessageHeader).extension("https://reportstream.cdc.gov/fhir/StructureDefinition/sender-id").value'
    valueSet:
      values:
        carbon-health: Carbon Health
    hl7Spec: [ MSH-4-1 ]

  - name: sending-facility-universal-id
    value:
     - 'Bundle.entry.resource.ofType(MessageHeader).extension("https://reportstream.cdc.gov/fhir/StructureDefinition/sender-id").value'
    valueSet:
      values:
        carbon-health: 05D2121942
    hl7Spec: [ MSH-4-2 ]

  - name: sending-facility-universal-id-type
    value:
     - 'Bundle.entry.resource.ofType(MessageHeader).extension("https://reportstream.cdc.gov/fhir/StructureDefinition/sender-id").value'
    valueSet:
      values:
        carbon-health: CLIA
    hl7Spec: [ MSH-4-3 ]
```
