### ISSUE TITLE
DevSecOps : Azure Monitoring Strategies

### ISSUE THREAD

**Issue by emvaldes** [CDCgov/prime-reportstream#16998]

**Comment by emvaldes** [comment]
---

#### **1. Query for API Performance Metrics**
Monitor API response times and failure rates.

```kql
requests
| where timestamp > ago(1h)
| summarize AvgResponseTime = avg(duration), FailureRate = countif(success == false) * 100.0 / count() by bin(timestamp, 1m)
| order by timestamp asc
```

---

#### **2. Query for Resource Utilization**
Monitor CPU, memory, and disk usage across VMs or containers.

```kql
Perf
| where ObjectName == "Processor" and CounterName == "% Processor Time"
| summarize AvgCPU = avg(CounterValue) by bin(TimeGenerated, 1m), Computer
| order by TimeGenerated asc
```

---

#### **3. Query for Dependency Performance**
Analyze database or external API dependency performance.

```kql
dependencies
| where timestamp > ago(1h)
| summarize AvgDependencyDuration = avg(duration), FailureRate = countif(success == false) * 100.0 / count() by bin(timestamp, 1m), name
| order by AvgDependencyDuration desc
```

---

#### **4. Query for Throughput (Requests/Second)**
Calculate the number of requests processed per second.

```kql
requests
| where timestamp > ago(1h)
| summarize Throughput = count() by bin(timestamp, 1s)
| order by timestamp asc
```

---

#### **5. Query for Error Rates**
Identify endpoints with high error rates.

```kql
requests
| where success == false
| summarize ErrorCount = count() by name, resultCode
| order by ErrorCount desc
```

---

#### **6. Query for Latency Trends**
Monitor latency trends over time.

```kql
requests
| where timestamp > ago(1h)
| summarize AvgLatency = avg(duration) by bin(timestamp, 1m)
| order by timestamp asc
```

---

### **Configuring Automation in GitHub Actions for Scalability Testing**

You can automate scalability testing in **GitHub Actions** using a load-testing tool like **Locust**, **Apache JMeter**, or **K6**.

---

#### **Sample GitHub Actions Workflow**
This example integrates Locust for load testing and stores the results in a file for further analysis.

```yaml
name: Scalability Testing

on:
  push:
    branches:
      - main

jobs:
  scalability-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment (for Locust)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Install Locust
      - name: Install Locust
        run: pip install locust

      # Run Locust load test
      - name: Run Load Test
        run: |
          locust -f tests/load_test.py --headless -u 100 -r 10 --run-time 10m --csv locust_results

      # Upload test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: locust-results
          path: locust_results_*.csv
```

---

#### **Key Points**
1. Replace `tests/load_test.py` with your custom Locust script.
2. Adjust the `-u` (number of users) and `-r` (spawn rate) flags to simulate different traffic levels.
3. Upload the results to an artifact repository for automated reporting.

---

### **Simulating Pandemic-Level Traffic**

To simulate **pandemic-level traffic**, use load testing tools that can scale traffic patterns to extreme levels. Here’s how to proceed:

#### **Step 1: Define Traffic Multipliers**
- Use historical data or assumptions to define traffic multipliers.
  - Example: 5x, 10x, 20x the normal traffic volume.

#### **Step 2: Simulate Spikes and Sustained Loads**
- **Spikes**:
  - Sudden traffic bursts over a short time (e.g., all requests within 5 minutes).
- **Sustained Loads**:
  - Consistent high traffic for an extended period (e.g., 6–12 hours).

#### **Step 3: Tools for Simulating Traffic**
1. **Azure Load Testing**:
   - Integrates with Azure resources and simulates large-scale traffic.
2. **Locust**:
   - Python-based tool for simulating user behavior and load patterns.
3. **Apache JMeter**:
   - Good for simulating high traffic on APIs and web services.
4. **K6**:
   - Lightweight tool for load testing scripts.

#### **Step 4: Configure Test Scenarios**
- Use realistic traffic patterns:
  - Randomized user behavior.
  - Mix of small and large batch requests.
- Include edge cases (e.g., largest possible batch size).

---

### **Metrics to Prioritize Monitoring**

For scalability testing, prioritize the following metrics:

#### **1. Performance Metrics**
- **Throughput**: Number of requests, batches, or transactions processed per second.
- **Latency**:
  - Average latency: Mean response time for requests.
  - 95th/99th percentile latency: Tail-end latencies that affect user experience.

#### **2. Resource Utilization**
- **CPU Usage**:
  - Percentage of CPU utilization across servers or containers.
- **Memory Usage**:
  - Percentage of memory used by key components (e.g., database, application servers).
- **I/O Performance**:
  - Disk IOPS (Input/Output Operations Per Second).
  - Network bandwidth utilization.

#### **3. Error Metrics**
- **Error Rate**:
  - Percentage of failed requests or batches.
- **Retries**:
  - Number of retried operations due to transient failures.

#### **4. Scalability Metrics**
- **Auto-Scaling Events**:
  - Number of instances added or removed during load tests.
- **Elasticity**:
  - Time taken to scale up or down during traffic spikes.

#### **5. Stability Metrics**
- **System Uptime**:
  - Percentage of time the system remains operational.
- **Resource Leaks**:
  - Gradual increases in memory or CPU usage during long-running tests (soak testing).

**Comment by emvaldes** [comment]
### **Sample Dashboards for Azure Monitor**

Here are key dashboard ideas you can create in **Azure Monitor** to track scalability and performance metrics:

---

#### **1. Throughput and Latency Dashboard**
- **Widgets**:
  1. **Throughput**: Visualize the number of requests processed per second using a Line Chart.
     ```kql
     requests
     | summarize Throughput = count() by bin(timestamp, 1m)
     ```
  2. **Latency**: Display average latency over time using a Line Chart.
     ```kql
     requests
     | summarize AvgLatency = avg(duration) by bin(timestamp, 1m)
     ```

- **Dashboard Example**:
  - Combine these metrics into a multi-line chart:
    - X-axis: Time (1-minute bins).
    - Y-axis: Throughput (requests/sec) and Latency (ms).

---

#### **2. Resource Utilization Dashboard**
- **Widgets**:
  1. **CPU Usage**: Bar Chart showing CPU utilization for VMs or containers.
     ```kql
     Perf
     | where ObjectName == "Processor" and CounterName == "% Processor Time"
     | summarize AvgCPU = avg(CounterValue) by Computer, bin(TimeGenerated, 1m)
     ```
  2. **Memory Usage**: Bar Chart showing memory usage across resources.
     ```kql
     Perf
     | where CounterName == "Available MBytes"
     | summarize AvgMemory = avg(CounterValue) by Computer, bin(TimeGenerated, 1m)
     ```

---

#### **3. Error Rate and Dependency Dashboard**
- **Widgets**:
  1. **Error Rates**: Pie Chart of errors by API endpoint.
     ```kql
     requests
     | where success == false
     | summarize ErrorCount = count() by name
     ```
  2. **Dependency Latency**: Bar Chart of average dependency latency.
     ```kql
     dependencies
     | summarize AvgDependencyLatency = avg(duration) by name
     ```

---

### **GitHub Actions Workflow for Load Testing**

#### **Integrating K6 into GitHub Actions**

Here’s a sample **GitHub Actions workflow** for running K6 load tests.

```yaml
name: Load Testing with K6

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install K6
      - name: Install K6
        run: sudo apt-get update && sudo apt-get install -y k6

      # Run K6 Load Test
      - name: Run K6 Test
        run: |
          k6 run --vus 100 --duration 10m load_test_script.js

      # Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: ./results.json
```

**Key Points**:
1. Replace `load_test_script.js` with your K6 load testing script.
2. Adjust the `--vus` (virtual users) and `--duration` flags to simulate different traffic loads.

---

#### **Integrating JMeter into GitHub Actions**

Here’s a sample **GitHub Actions workflow** for running JMeter load tests.

```yaml
name: Load Testing with JMeter

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install JMeter
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          sudo mv apache-jmeter-5.5 /usr/local/jmeter

      # Run JMeter Load Test
      - name: Run JMeter Test
        run: |
          /usr/local/jmeter/bin/jmeter -n -t load_test_plan.jmx -l results.jtl

      # Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: ./results.jtl
```

**Key Points**:
1. Replace `load_test_plan.jmx` with your custom JMeter test plan.
2. Results (`results.jtl`) can be uploaded as artifacts for further analysis.

---

### **Chaos Testing Implementation Details**

Chaos testing focuses on validating a system's resilience by injecting failures in a controlled manner. Here's how to implement chaos testing:

---

#### **1. Choose Chaos Testing Tool**
- **Azure Chaos Studio**:
  - Azure-native tool for fault injection into VMs, AKS, and other Azure services.
- **Gremlin**:
  - Comprehensive chaos engineering platform for simulating failures.
- **LitmusChaos**:
  - Open-source tool for Kubernetes environments.

---

#### **2. Plan Chaos Experiments**
1. **Define Objectives**:
   - Validate system recovery from:
     - VM crashes.
     - Database node failures.
     - Network latency spikes.
2. **Identify Scenarios**:
   - Example scenarios:
     - Shut down 1 of 3 database nodes.
     - Simulate 200ms additional latency in the API gateway.
     - Drop 10% of network packets for a specific service.

---

#### **3. Execute Chaos Experiments**
1. **Azure Chaos Studio Setup**:
   - Enable Chaos Studio in the Azure Portal.
   - Attach resources (e.g., VMs, AKS) to Chaos Studio targets.
2. **Run Experiments**:
   - Example: Shutdown VM experiment.
     ```bash
     az chaos experiment create --name shutdown-vm --resource-group my-rg --parameters <experiment-config>
     ```

---

#### **4. Validate Results**
- **Monitor Metrics**:
  - Use Azure Monitor or Application Insights to track system recovery during chaos experiments.
- **Document Observations**:
  - Recovery time, impact on latency, error rates.

---

### **Key Metrics for Monitoring Chaos Tests**
1. **Recovery Time Objective (RTO)**:
   - Time taken for the system to recover from a failure.
2. **Error Rate During Failure**:
   - Percentage of failed requests during the chaos test.
3. **Impact on Latency**:
   - Increase in latency caused by the failure.
4. **Auto-Scaling Efficiency**:
   - Time taken to add/remove resources during the chaos test.
