### ISSUE TITLE
DevSecOps : Implementation Stages

### ISSUE THREAD

**Issue by emvaldes** [CDCgov/prime-reportstream#16997]
Let’s break down **implementation plans for specific recommendations** based on the findings from the evaluation report. These plans include actionable steps, tools, and expected outcomes to ensure each recommendation is effectively implemented.

**Comment by emvaldes** [comment]
### **1. Infrastructure Implementation Plan**
#### **Objective**: Address critical infrastructure gaps such as encryption, patching, and network security.

##### **Actions**:
1. **Enable Encryption for All Storage Accounts**:
   - Use **Azure Policy** to enforce encryption at rest:
     - Create a policy definition with `"enforceEncryption"` to ensure all storage accounts use Azure-managed keys or customer-managed keys (CMK).
     - Assign the policy to the appropriate scope (resource group or subscription).
   - Use Terraform to reconfigure existing storage accounts:
     ```hcl
     resource "azurerm_storage_account" "example" {
       name                     = "examplestorage"
       resource_group_name      = "example-rg"
       location                 = "eastus"
       account_tier             = "Standard"
       account_replication_type = "LRS"

       enable_https_traffic_only = true
       allow_blob_public_access  = false

       blob_properties {
         delete_retention_policy {
           days = 7
         }
       }
     }
     ```
   - Verify compliance using Azure Security Center.

2. **Patch Virtual Machines**:
   - Use **Azure Update Management** to automate patching:
     - Onboard all VMs into Update Management via the **Azure Automation Account**.
     - Schedule a patch deployment plan for critical updates.
   - Verify patch status via **Azure Log Analytics**.

3. **Harden Network Security**:
   - Create Network Security Groups (NSGs) using Terraform:
     ```hcl
     resource "azurerm_network_security_group" "example" {
       name                = "example-nsg"
       location            = "eastus"
       resource_group_name = "example-rg"

       security_rule {
         name                       = "Deny-All-Inbound"
         priority                   = 100
         direction                  = "Inbound"
         access                     = "Deny"
         protocol                   = "*"
         source_port_range          = "*"
         destination_port_range     = "*"
         source_address_prefix      = "*"
         destination_address_prefix = "*"
       }
     }
     ```
   - Apply NSGs to subnets and public-facing VMs.

##### **Expected Outcomes**:
- Full compliance with encryption and patching policies.
- Secured network boundaries for public and private resources.

---

### **2. CI/CD Pipeline Implementation Plan**
#### **Objective**: Enhance security and efficiency in GitHub Actions workflows.

##### **Actions**:
1. **Secure Secrets Management**:
   - Integrate GitHub Actions with **Azure Key Vault**:
     - Set up an Azure Key Vault and store all sensitive data (e.g., API keys, Terraform state keys).
     - Use OpenID Connect (OIDC) for authentication between GitHub and Azure:
       ```yaml
       permissions:
         id-token: write
         contents: read

       steps:
       - name: Login to Azure
         uses: azure/login@v1
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           federated-credential: ${{ secrets.AZURE_FEDERATED_CREDENTIAL }}
       ```
   - Update existing workflows to fetch secrets from Key Vault dynamically.

2. **Add Security Scans**:
   - Integrate **CodeQL** for Static Application Security Testing (SAST):
     ```yaml
     name: CodeQL Analysis

     on:
       push:
         branches: [ main ]
       pull_request:
         branches: [ main ]

     jobs:
       analyze:
         runs-on: ubuntu-latest
         steps:
         - name: Checkout repository
           uses: actions/checkout@v3
         - name: Initialize CodeQL
           uses: github/codeql-action/init@v2
           with:
             languages: ['javascript', 'python']
         - name: Perform CodeQL Analysis
           uses: github/codeql-action/analyze@v2
     ```

3. **Optimize Terraform Workflows**:
   - Standardize Terraform jobs to include validation and linting:
     ```yaml
     jobs:
       terraform:
         runs-on: ubuntu-latest
         steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Terraform Init
           run: terraform init

         - name: Terraform Validate
           run: terraform validate

         - name: Terraform Plan
           run: terraform plan
     ```
   - Use tools like `tflint` and `terrascan` to ensure compliance with best practices.

##### **Expected Outcomes**:
- Secure handling of secrets in CI/CD pipelines.
- Early detection of vulnerabilities via automated security scans.
- Consistent and error-free Terraform deployments.

---

### **3. Application & Workload Implementation Plan**
#### **Objective**: Optimize data processing pipelines and secure APIs.

##### **Actions**:
1. **Optimize Azure Event Hub**:
   - Increase throughput units or enable **Auto-Inflate**:
     ```hcl
     resource "azurerm_eventhub_namespace" "example" {
       name                = "example-namespace"
       location            = "eastus"
       resource_group_name = "example-rg"
       sku                 = "Standard"
       capacity            = 2
       auto_inflate_enabled = true
       maximum_throughput_units = 20
     }
     ```

2. **Harden APIs**:
   - Protect APIs with **Azure API Management**:
     - Import all API endpoints into Azure API Management.
     - Configure rate limiting and IP restrictions:
       ```hcl
       resource "azurerm_api_management" "example" {
         name                = "example-api-management"
         location            = "eastus"
         resource_group_name = "example-rg"
         publisher_email     = "admin@example.com"
         publisher_name      = "Example Publisher"

         identity {
           type = "SystemAssigned"
         }
       }
       ```
   - Implement OAuth2.0 for API authentication.

3. **Investigate Latency Issues**:
   - Use **Azure Application Insights**:
     - Enable dependency tracking and monitor API call response times.
     - Set alerts for latency thresholds exceeding 300ms.
   - Optimize database queries or implement caching mechanisms.

##### **Expected Outcomes**:
- Scalable and efficient data ingestion pipelines.
- Secured APIs with rate limiting and authentication.
- Reduced API latency for improved user experience.

---

### **Next Steps**
1. Implement the **Infrastructure Plan** immediately to address critical security and compliance gaps.
2. Develop a **pilot CI/CD pipeline** with GitHub Actions improvements and test workflows.
3. Collaborate with the development team to address application-specific issues (e.g., API latency, data pipeline optimization).

**Comment by emvaldes** [comment]
### **CI/CD Pipeline Implementation Plan**
#### **Objective**: Enhance security and efficiency in GitHub Actions workflows.

##### **Actions**:
1. **Secure Secrets Management**:
   - Integrate GitHub Actions with **Azure Key Vault**:
     - Set up an Azure Key Vault and store all sensitive data (e.g., API keys, Terraform state keys).
     - Use OpenID Connect (OIDC) for authentication between GitHub and Azure:
       ```yaml
       permissions:
         id-token: write
         contents: read

       steps:
       - name: Login to Azure
         uses: azure/login@v1
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           federated-credential: ${{ secrets.AZURE_FEDERATED_CREDENTIAL }}
       ```
   - Update existing workflows to fetch secrets from Key Vault dynamically.

2. **Add Security Scans**:
   - Integrate **CodeQL** for Static Application Security Testing (SAST):
     ```yaml
     name: CodeQL Analysis

     on:
       push:
         branches: [ main ]
       pull_request:
         branches: [ main ]

     jobs:
       analyze:
         runs-on: ubuntu-latest
         steps:
         - name: Checkout repository
           uses: actions/checkout@v3
         - name: Initialize CodeQL
           uses: github/codeql-action/init@v2
           with:
             languages: ['javascript', 'python']
         - name: Perform CodeQL Analysis
           uses: github/codeql-action/analyze@v2
     ```

3. **Optimize Terraform Workflows**:
   - Standardize Terraform jobs to include validation and linting:
     ```yaml
     jobs:
       terraform:
         runs-on: ubuntu-latest
         steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Terraform Init
           run: terraform init

         - name: Terraform Validate
           run: terraform validate

         - name: Terraform Plan
           run: terraform plan
     ```
   - Use tools like `tflint` and `terrascan` to ensure compliance with best practices.

##### **Expected Outcomes**:
- Secure handling of secrets in CI/CD pipelines.
- Early detection of vulnerabilities via automated security scans.
- Consistent and error-free Terraform deployments.
