### ISSUE TITLE
DevSecOps : Chaos Engineering

### ISSUE THREAD

**Issue by emvaldes** [CDCgov/prime-reportstream#17000]

**Comment by emvaldes** [comment]
### **1. Configuring Azure Chaos Studio for Chaos Testing**

Azure Chaos Studio allows you to run controlled fault injection experiments. Here's a step-by-step guide to configure and execute experiments:

---

#### **Step 1: Enable Chaos Studio**
1. **Enable Chaos Studio**:
   - Go to the **Azure Portal** and search for "Chaos Studio."
   - Select **Enable Chaos Studio**.
   - Choose the **subscription** and **resources** you want to enable for experiments.

2. **Enable Target Resources**:
   - Attach the target resources (e.g., VMs, AKS, App Services) for experimentation.
   - For each resource, add the **Chaos Agent extension** if required.

---

#### **Step 2: Define a Chaos Experiment**
1. Go to **Chaos Studio** and create a new experiment.
2. **Add Targets**:
   - Select the resources to include in the experiment (e.g., VMs, AKS pods, App Services).
3. **Add Faults**:
   - Choose fault types:
     - **VM Shutdown**: Simulates a virtual machine being powered off.
     - **Network Latency**: Introduces additional latency for network requests.
     - **CPU Stress**: Consumes CPU resources on a VM.

4. **Configure Experiment Duration**:
   - Set the duration of each fault (e.g., 5 minutes, 10 minutes).

---

#### **Step 3: Execute the Chaos Experiment**
1. **Start the Experiment**:
   - Run the experiment manually or schedule it for later.
2. **Monitor the Progress**:
   - Use the Azure Portal to view real-time metrics and experiment execution logs.

---

#### **Step 4: Analyze Results**
1. Use **Azure Monitor** and **Application Insights** to measure the impact:
   - Latency spikes.
   - Error rates.
   - Auto-scaling events.
2. Record metrics for recovery time and system resilience.

---

### **2. Automating Chaos Experiments in CI/CD Pipelines**

You can integrate Azure Chaos Studio experiments into your CI/CD pipeline using Azure CLI or REST APIs.

---

#### **Using Azure CLI**
Here’s an example of automating a Chaos Studio experiment in a pipeline:

1. **Create an Experiment in JSON Format**:
   Save the experiment configuration as a `chaos-experiment.json` file.

   Example:
   ```json
   {
     "properties": {
       "selectors": [
         {
           "type": "List",
           "id": "target-selector",
           "targets": [
             "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Compute/virtualMachines/<VM_NAME>"
           ]
         }
       ],
       "steps": [
         {
           "name": "Shutdown VM",
           "type": "Continuous",
           "actions": [
             {
               "type": "Microsoft-VirtualMachine-Shutdown",
               "name": "Shutdown VM Action",
               "parameters": {
                 "duration": "PT5M"
               }
             }
           ]
         }
       ]
     }
   }
   ```

2. **Add CLI Commands to Your CI/CD Pipeline**:
   - Example using GitHub Actions:

   ```yaml
   name: Chaos Testing in CI/CD

   on:
     push:
       branches:
         - main

   jobs:
     chaos-test:
       runs-on: ubuntu-latest

       steps:
         # Checkout code
         - name: Checkout code
           uses: actions/checkout@v3

         # Login to Azure
         - name: Login to Azure
           uses: azure/login@v1
           with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}

         # Run Chaos Experiment
         - name: Run Chaos Experiment
           run: |
             az chaos experiment create --resource-group <RESOURCE_GROUP> --name shutdown-vm --parameters @chaos-experiment.json
             az chaos experiment start --resource-group <RESOURCE_GROUP> --name shutdown-vm
   ```

---

#### **Using REST API**
1. **Create a Chaos Experiment**:
   - Use the Azure REST API to programmatically create and start experiments.
   - Endpoint: `https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Chaos/experiments/{experimentName}?api-version=2021-09-15-preview`

2. **Start the Experiment**:
   - Send a `POST` request to start the experiment.
   - Include the experiment configuration in the request body.

---

### **3. Advanced Dashboards for Chaos Testing Metrics**

#### **A. Real-Time Monitoring Dashboard**
1. **Widgets**:
   - **Experiment Status**:
     - Monitor the status of running chaos experiments.
     - Query:
       ```kql
       customEvents
       | where name == "ChaosExperiment"
       | summarize Count = count() by experimentId, tostring(properties['status'])
       ```
   - **Error Rate During Test**:
     - Visualize errors by service during chaos tests.
       ```kql
       requests
       | where timestamp > ago(1h) and success == false
       | summarize ErrorCount = count() by bin(timestamp, 1m), name
       ```

---

#### **B. Resilience Validation Dashboard**
1. **Widgets**:
   - **Auto-Scaling Efficiency**:
     - Monitor the time taken for the system to scale up or down.
       ```kql
       customEvents
       | where name == "Scale Event"
       | summarize AvgScaleTime = avg(todouble(properties['timeToScale'])) by bin(timestamp, 1m)
       ```

   - **Service Availability**:
     - Track service uptime during chaos tests.
       ```kql
       requests
       | summarize UptimePercentage = countif(success == true) * 100.0 / count() by bin(timestamp, 1m)
       ```

---

### **4. Key Metrics to Monitor During Chaos Testing**
1. **Recovery Time Objective (RTO)**:
   - Time taken for the system to return to normal after fault injection.
2. **Service Availability**:
   - Percentage of requests successfully processed during the experiment.
3. **Latency Impact**:
   - Increase in average or tail-end latency (95th/99th percentile).
4. **Error Rates**:
   - Percentage of failed requests or transactions during the test.
5. **Scaling Efficiency**:
   - Time and accuracy of auto-scaling events triggered by the fault.

**Comment by emvaldes** [comment]
### **Detailed Guide for Setting Up Azure CLI Commands, REST API Integrations, and Custom Dashboards for Chaos Testing**

---

### **1. Setting Up Azure CLI Commands**

You can automate chaos testing experiments using Azure CLI commands. Below is a detailed walkthrough:

#### **Step 1: Prerequisites**
1. Install Azure CLI on your local machine or use a pipeline environment with Azure CLI installed.
   ```bash
   az version
   ```
2. Log in to Azure:
   ```bash
   az login
   ```
3. Ensure the **Chaos Studio** resource provider is registered:
   ```bash
   az provider register --namespace Microsoft.Chaos
   ```

---

#### **Step 2: Create Chaos Experiment with Azure CLI**
1. Define the experiment configuration in a JSON file (`chaos-experiment.json`):
   ```json
   {
     "properties": {
       "selectors": [
         {
           "type": "List",
           "id": "target-selector",
           "targets": [
             "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Compute/virtualMachines/<VM_NAME>"
           ]
         }
       ],
       "steps": [
         {
           "name": "Shutdown VM",
           "type": "Continuous",
           "actions": [
             {
               "type": "Microsoft-VirtualMachine-Shutdown",
               "name": "Shutdown VM Action",
               "parameters": {
                 "duration": "PT5M"
               }
             }
           ]
         }
       ]
     }
   }
   ```

2. Use Azure CLI to create the experiment:
   ```bash
   az chaos experiment create \
       --resource-group <RESOURCE_GROUP> \
       --name shutdown-vm-test \
       --parameters @chaos-experiment.json
   ```

3. Start the experiment:
   ```bash
   az chaos experiment start \
       --resource-group <RESOURCE_GROUP> \
       --name shutdown-vm-test
   ```

4. Monitor the experiment status:
   ```bash
   az chaos experiment show \
       --resource-group <RESOURCE_GROUP> \
       --name shutdown-vm-test
   ```

5. Stop the experiment (if needed):
   ```bash
   az chaos experiment stop \
       --resource-group <RESOURCE_GROUP> \
       --name shutdown-vm-test
   ```

---

### **2. REST API Integration for Chaos Testing**

#### **Step 1: Create an Experiment with REST API**
1. Use the following endpoint to create an experiment:
   - Endpoint:
     ```
     POST https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Chaos/experiments/<EXPERIMENT_NAME>?api-version=2021-09-15-preview
     ```

2. Include the experiment definition in the request body:
   ```json
   {
     "location": "eastus",
     "properties": {
       "selectors": [
         {
           "type": "List",
           "id": "target-selector",
           "targets": [
             "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Compute/virtualMachines/<VM_NAME>"
           ]
         }
       ],
       "steps": [
         {
           "name": "Shutdown VM",
           "type": "Continuous",
           "actions": [
             {
               "type": "Microsoft-VirtualMachine-Shutdown",
               "name": "Shutdown VM Action",
               "parameters": {
                 "duration": "PT5M"
               }
             }
           ]
         }
       ]
     }
   }
   ```

3. Use `curl` or any HTTP client to send the request:
   ```bash
   curl -X POST \
     -H "Authorization: Bearer <ACCESS_TOKEN>" \
     -H "Content-Type: application/json" \
     -d @chaos-experiment.json \
     "https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Chaos/experiments/<EXPERIMENT_NAME>?api-version=2021-09-15-preview"
   ```

4. Start the experiment:
   - Endpoint:
     ```
     POST https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Chaos/experiments/<EXPERIMENT_NAME>/start?api-version=2021-09-15-preview
     ```

   Example `curl` request:
   ```bash
   curl -X POST \
     -H "Authorization: Bearer <ACCESS_TOKEN>" \
     -H "Content-Type: application/json" \
     "https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Chaos/experiments/<EXPERIMENT_NAME>/start?api-version=2021-09-15-preview"
   ```

---

### **3. Custom Dashboards for Chaos Testing Metrics**

#### **A. Create Azure Monitor Workbooks**
1. **Access Azure Workbooks**:
   - Navigate to **Azure Monitor > Workbooks**.
   - Create a new workbook and select the appropriate resource (e.g., VM, AKS).

2. **Add Key Queries for Chaos Metrics**:
   - **Service Availability**:
     ```kql
     requests
     | summarize Availability = countif(success == true) * 100.0 / count() by bin(timestamp, 1m)
     ```
   - **Recovery Time**:
     ```kql
     customEvents
     | where name == "ChaosExperiment"
     | summarize RecoveryTime = max(timestamp) - min(timestamp) by experimentId
     ```
   - **Auto-Scaling Events**:
     ```kql
     customEvents
     | where name == "Scale Event"
     | summarize ScaleUps = countif(eventType == "ScaleUp"), ScaleDowns = countif(eventType == "ScaleDown") by bin(timestamp, 1m)
     ```

3. **Visualizations**:
   - Add line charts for service availability and recovery time.
   - Add bar or pie charts for auto-scaling events.

---

#### **B. Example Dashboard Components**
1. **Line Chart**: Service Availability During Chaos Tests.
2. **Bar Chart**: Number of Auto-Scaling Events (Scale Up/Down).
3. **Pie Chart**: Error Distribution During Chaos Tests.

---

### **4. Automating Chaos Tests in CI/CD Pipelines**

#### **Example GitHub Actions Workflow**
Integrate chaos testing into CI/CD pipelines for validation after deployments.

```yaml
name: Chaos Testing Workflow

on:
  push:
    branches:
      - main

jobs:
  chaos-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run Chaos Experiment
      - name: Start Chaos Experiment
        run: |
          az chaos experiment start \
            --resource-group <RESOURCE_GROUP> \
            --name shutdown-vm-test

      # Monitor Results
      - name: Get Experiment Status
        run: |
          az chaos experiment show \
            --resource-group <RESOURCE_GROUP> \
            --name shutdown-vm-test
```

**Comment by emvaldes** [comment]
### **3. Advanced Dashboards for Chaos Testing Metrics**

#### **A. Real-Time Monitoring Dashboard**
1. **Widgets**:
   - **Experiment Status**:
     - Monitor the status of running chaos experiments.
     - Query:
       ```kql
       customEvents
       | where name == "ChaosExperiment"
       | summarize Count = count() by experimentId, tostring(properties['status'])
       ```
   - **Error Rate During Test**:
     - Visualize errors by service during chaos tests.
       ```kql
       requests
       | where timestamp > ago(1h) and success == false
       | summarize ErrorCount = count() by bin(timestamp, 1m), name
       ```

---

#### **B. Resilience Validation Dashboard**
1. **Widgets**:
   - **Auto-Scaling Efficiency**:
     - Monitor the time taken for the system to scale up or down.
       ```kql
       customEvents
       | where name == "Scale Event"
       | summarize AvgScaleTime = avg(todouble(properties['timeToScale'])) by bin(timestamp, 1m)
       ```

   - **Service Availability**:
     - Track service uptime during chaos tests.
       ```kql
       requests
       | summarize UptimePercentage = countif(success == true) * 100.0 / count() by bin(timestamp, 1m)
       ```

**Comment by emvaldes** [comment]
### **Detailed Guide for Setting Up Azure CLI Commands, REST API Integrations, and Custom Dashboards for Chaos Testing**

**Comment by emvaldes** [comment]
### Setting Up Azure CLI Commands, REST API Integrations, and Custom Dashboards for Chaos Testing

**Comment by emvaldes** [comment]
### **1. Setting Up Azure CLI Commands**

You can automate chaos testing experiments using Azure CLI commands. Below is a detailed walkthrough:

#### **Step 1: Prerequisites**
1. Install Azure CLI on your local machine or use a pipeline environment with Azure CLI installed.
   ```bash
   az version
   ```
2. Log in to Azure:
   ```bash
   az login
   ```
3. Ensure the **Chaos Studio** resource provider is registered:
   ```bash
   az provider register --namespace Microsoft.Chaos
   ```

**Comment by emvaldes** [comment]
#### **Step 2: Create Chaos Experiment with Azure CLI**
1. Define the experiment configuration in a JSON file (`chaos-experiment.json`):
   ```json
   {
     "properties": {
       "selectors": [
         {
           "type": "List",
           "id": "target-selector",
           "targets": [
             "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Compute/virtualMachines/<VM_NAME>"
           ]
         }
       ],
       "steps": [
         {
           "name": "Shutdown VM",
           "type": "Continuous",
           "actions": [
             {
               "type": "Microsoft-VirtualMachine-Shutdown",
               "name": "Shutdown VM Action",
               "parameters": {
                 "duration": "PT5M"
               }
             }
           ]
         }
       ]
     }
   }
   ```

2. Use Azure CLI to create the experiment:
   ```bash
   az chaos experiment create \
       --resource-group <RESOURCE_GROUP> \
       --name shutdown-vm-test \
       --parameters @chaos-experiment.json
   ```

3. Start the experiment:
   ```bash
   az chaos experiment start \
       --resource-group <RESOURCE_GROUP> \
       --name shutdown-vm-test
   ```

4. Monitor the experiment status:
   ```bash
   az chaos experiment show \
       --resource-group <RESOURCE_GROUP> \
       --name shutdown-vm-test
   ```

5. Stop the experiment (if needed):
   ```bash
   az chaos experiment stop \
       --resource-group <RESOURCE_GROUP> \
       --name shutdown-vm-test
   ```

**Comment by emvaldes** [comment]
### **Custom Dashboards for Chaos Testing Metrics**

#### **A. Create Azure Monitor Workbooks**
1. **Access Azure Workbooks**:
   - Navigate to **Azure Monitor > Workbooks**.
   - Create a new workbook and select the appropriate resource (e.g., VM, AKS).

2. **Add Key Queries for Chaos Metrics**:
   - **Service Availability**:
     ```kql
     requests
     | summarize Availability = countif(success == true) * 100.0 / count() by bin(timestamp, 1m)
     ```
   - **Recovery Time**:
     ```kql
     customEvents
     | where name == "ChaosExperiment"
     | summarize RecoveryTime = max(timestamp) - min(timestamp) by experimentId
     ```
   - **Auto-Scaling Events**:
     ```kql
     customEvents
     | where name == "Scale Event"
     | summarize ScaleUps = countif(eventType == "ScaleUp"), ScaleDowns = countif(eventType == "ScaleDown") by bin(timestamp, 1m)
     ```

3. **Visualizations**:
   - Add line charts for service availability and recovery time.
   - Add bar or pie charts for auto-scaling events.

---

#### **B. Example Dashboard Components**
1. **Line Chart**: Service Availability During Chaos Tests.
2. **Bar Chart**: Number of Auto-Scaling Events (Scale Up/Down).
3. **Pie Chart**: Error Distribution During Chaos Tests.

**Comment by emvaldes** [comment]
### **Automating Chaos Tests in CI/CD Pipelines**

#### **Example GitHub Actions Workflow**
Integrate chaos testing into CI/CD pipelines for validation after deployments.

```yaml
name: Chaos Testing Workflow

on:
  push:
    branches:
      - main

jobs:
  chaos-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run Chaos Experiment
      - name: Start Chaos Experiment
        run: |
          az chaos experiment start \
            --resource-group <RESOURCE_GROUP> \
            --name shutdown-vm-test

      # Monitor Results
      - name: Get Experiment Status
        run: |
          az chaos experiment show \
            --resource-group <RESOURCE_GROUP> \
            --name shutdown-vm-test
```
