### ISSUE TITLE
DevSecOps : Improve Existing API Documentation (Swagger)

### ISSUE THREAD

**Issue by emvaldes** [CDCgov/prime-reportstream#17010]
#### **Objective:**
Enhance the quality and usability of API documentation to ensure it is accurate, user-friendly, and up-to-date. Use tools like Swagger/OpenAPI to make the documentation interactive and accessible for developers and stakeholders.

**Comment by emvaldes** [comment]
### **Evaluate Current API Documentation**
**Goal**: Assess the state of existing API documentation and identify gaps.

---

**Tasks:**
1. **Audit Existing Documentation**
   - **Sub-Tasks**:
     1. Review current API documentation for all endpoints (REST/GraphQL/etc.).
     2. Identify missing endpoints, outdated descriptions, or incomplete details.
     3. Check for inconsistencies in parameter definitions, request/response formats, and status codes.

2. **Gather Feedback from Stakeholders**
   - **Sub-Tasks**:
     1. Interview API consumers (internal teams or external users) to understand pain points in the current documentation.
     2. Collect feedback on missing features or usability challenges.

3. **Define Documentation Standards**
   - **Sub-Tasks**:
     1. Agree on standards for API documentation (e.g., use OpenAPI Specification).
     2. Define a consistent format for endpoint descriptions, example payloads, and status codes.

**Comment by emvaldes** [comment]
### **Set Up Swagger/OpenAPI for Documentation**
**Goal**: Deploy Swagger/OpenAPI tools to generate and host interactive API documentation.

---

**Tasks:**
1. **Install Swagger/OpenAPI Tools**
   - **Sub-Tasks**:
     1. Add Swagger dependencies to the codebase:
        - For Node.js: `swagger-jsdoc` and `swagger-ui-express`.
        - For Python: `Flask-RESTPlus` or `FastAPI`.
        - For Java: Springfox or Swagger Core.
     2. Ensure the project includes an OpenAPI-compliant JSON/YAML file.

2. **Create a Centralized Documentation Repository**
   - **Sub-Tasks**:
     1. Use SwaggerHub or similar tools for collaborative documentation management.
     2. Integrate the OpenAPI specification into version control (e.g., GitHub).

3. **Host Documentation**
   - **Sub-Tasks**:
     1. Set up Swagger UI for interactive documentation.
     2. Deploy the documentation on an accessible endpoint (e.g., `/api-docs`).

**Comment by emvaldes** [comment]
### **Automate API Documentation Updates**
**Goal**: Ensure API documentation remains up-to-date with code changes.

---

**Tasks:**
1. **Integrate Documentation Generation into CI/CD**
   - **Sub-Tasks**:
     1. Automate OpenAPI specification updates during API development.
     2. Validate OpenAPI files in pull requests to ensure compliance.

2. **Enable Live Sync**
   - **Sub-Tasks**:
     1. Use tools like `swagger-autogen` or `drf-yasg` to generate documentation directly from the codebase.
     2. Monitor for changes in code and regenerate documentation dynamically.

3. **Schedule Regular Documentation Reviews**
   - **Sub-Tasks**:
     1. Assign a periodic review process for API documentation.
     2. Ensure documentation is audited before major releases.

**Comment by emvaldes** [comment]
### **Make API Documentation Developer-Friendly**
**Goal**: Ensure the documentation is accessible and easy to use for developers.

---

**Tasks:**
1. **Add Interactive Features**
   - **Sub-Tasks**:
     1. Enable "Try It Out" functionality in Swagger UI to let users test endpoints.
     2. Provide auto-generated code snippets for popular languages (e.g., Python, JavaScript, Java).

2. **Improve Navigation**
   - **Sub-Tasks**:
     1. Organize endpoints into logical groups (e.g., Users, Orders, Payments).
     2. Add a search feature to quickly find endpoints or keywords.

3. **Provide Developer Guides**
   - **Sub-Tasks**:
     1. Include a "Getting Started" section with setup instructions and API keys.
     2. Add FAQs or troubleshooting tips for common issues.

**Comment by emvaldes** [comment]
### **Deliverables**
1. Centralized API documentation in Swagger/OpenAPI format.
2. Interactive documentation hosted at a publicly accessible endpoint (e.g., `/api-docs`).
3. Automated updates for API documentation as part of CI/CD workflows.
4. Developer-friendly features like interactive testing and code snippets.

---

### **Integration with Existing Sections**
- **Adopt and Deploy Load Testing Framework**:
  - Document batch processing APIs and endpoints for easy load testing setup.
- **Reproduce Production Environment**:
  - Use detailed API documentation to replicate API dependencies in staging.
- **Batch Size and Concurrency Testing**:
  - Include endpoints and request/response examples to support these tests.

**Comment by emvaldes** [comment]
### **Integration with Existing Sections**
- **Adopt and Deploy Load Testing Framework**:
  - Document batch processing APIs and endpoints for easy load testing setup.
- **Reproduce Production Environment**:
  - Use detailed API documentation to replicate API dependencies in staging.
- **Batch Size and Concurrency Testing**:
  - Include endpoints and request/response examples to support these tests.

**Comment by emvaldes** [comment]
### **Swagger/OpenAPI Tooling Examples**

**Comment by emvaldes** [comment]
#### **1. Node.js Example with Swagger**
Add Swagger to a Node.js project:
```javascript
const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');
const express = require('express');

const app = express();

// Swagger definition
const swaggerDefinition = {
  openapi: '3.0.0',
  info: {
    title: 'API Documentation',
    version: '1.0.0',
    description: 'Interactive API documentation for our project',
  },
  servers: [
    { url: 'https://your-api-url.com', description: 'Production server' },
  ],
};

const options = {
  swaggerDefinition,
  apis: ['./routes/*.js'], // Point to your API route files
};

const swaggerSpec = swaggerJsdoc(options);

// Serve Swagger UI
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

app.listen(3000, () => {
  console.log('API docs available at http://localhost:3000/api-docs');
});
```

**Comment by emvaldes** [comment]
#### **2. Python Example with FastAPI**
FastAPI automatically generates Swagger documentation:
```python
from fastapi import FastAPI

app = FastAPI()

@app.get("/items/{item_id}")
async def read_item(item_id: int, q: str = None):
    return {"item_id": item_id, "q": q}

# Access Swagger UI at: http://127.0.0.1:8000/docs
# Access OpenAPI JSON at: http://127.0.0.1:8000/openapi.json
```

**Comment by emvaldes** [comment]
### **Recommendations for Improving API Documentation with Swagger/OpenAPI**

Here’s an in-depth guide covering **tooling setup**, **automated updates in CI/CD pipelines**, and **specific examples for different programming languages**.

**Comment by emvaldes** [comment]
### **Tooling Setup for Swagger/OpenAPI**

#### **A. Setting Up Swagger for Different Frameworks**

1. **Node.js Example with Swagger**
   Use `swagger-jsdoc` and `swagger-ui-express` to set up Swagger in a Node.js application.

   ```javascript
   const swaggerJsdoc = require('swagger-jsdoc');
   const swaggerUi = require('swagger-ui-express');
   const express = require('express');

   const app = express();

   // Swagger Definition
   const swaggerDefinition = {
     openapi: '3.0.0',
     info: {
       title: 'API Documentation',
       version: '1.0.0',
       description: 'Interactive API documentation for our project',
     },
     servers: [
       { url: 'https://your-api-url.com', description: 'Production server' },
       { url: 'http://localhost:3000', description: 'Local server' },
     ],
   };

   const options = {
     swaggerDefinition,
     apis: ['./routes/*.js'], // Specify API route files here
   };

   const swaggerSpec = swaggerJsdoc(options);

   // Swagger UI Middleware
   app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

   app.listen(3000, () => {
     console.log('API documentation available at http://localhost:3000/api-docs');
   });
   ```

   Key Steps:
   - Add comments in route files to generate API specs dynamically.
   - Route example:
     ```javascript
     /**
      * @swagger
      * /users:
      *   get:
      *     summary: Get a list of users
      *     responses:
      *       200:
      *         description: A JSON array of user objects
      */
     app.get('/users', (req, res) => {
       res.send([{ id: 1, name: 'John' }]);
     });
     ```

---

2. **Python Example with FastAPI**
   FastAPI natively supports Swagger UI and OpenAPI specifications without additional setup.

   ```python
   from fastapi import FastAPI

   app = FastAPI()

   @app.get("/items/{item_id}")
   async def read_item(item_id: int, q: str = None):
       return {"item_id": item_id, "q": q}

   # Access Swagger UI at: http://127.0.0.1:8000/docs
   # Access OpenAPI JSON at: http://127.0.0.1:8000/openapi.json
   ```

---

3. **Java Example with Spring Boot**
   Use `springdoc-openapi` to generate OpenAPI documentation for a Spring Boot project.

   - Add the dependency in `pom.xml`:
     ```xml
     <dependency>
       <groupId>org.springdoc</groupId>
       <artifactId>springdoc-openapi-ui</artifactId>
       <version>1.6.14</version>
     </dependency>
     ```

   - Enable Swagger UI in the application by adding the following configuration:
     ```java
     @RestController
     @RequestMapping("/api/v1")
     public class UserController {

         @GetMapping("/users")
         public List<User> getUsers() {
             return List.of(new User(1, "John"), new User(2, "Jane"));
         }
     }
     ```

   - Swagger UI will be available at: `http://localhost:8080/swagger-ui.html`

---

4. **Django Example with drf-yasg**
   Use `drf-yasg` for Swagger documentation in Django REST Framework.

   - Install the library:
     ```bash
     pip install drf-yasg
     ```

   - Add the following code to `urls.py`:
     ```python
     from django.urls import path
     from rest_framework import permissions
     from drf_yasg.views import get_schema_view
     from drf_yasg import openapi

     schema_view = get_schema_view(
         openapi.Info(
             title="API Documentation",
             default_version="v1",
             description="Interactive API documentation",
         ),
         public=True,
         permission_classes=(permissions.AllowAny,),
     )

     urlpatterns = [
         path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
     ]
     ```

**Comment by emvaldes** [comment]
#### **B. Publishing Documentation**
1. Use SwaggerHub or similar tools to publish OpenAPI specs automatically during deployments.
2. Host generated Swagger UI using GitHub Pages or an S3 bucket.

**Comment by emvaldes** [comment]
#### **C. Regular Validation**
1. Integrate OpenAPI spec validation into pull requests:
   - Use `swagger-cli` to validate specs.
   ```bash
   npm install -g swagger-cli
   swagger-cli validate swagger-output.json
   ```

2. Trigger documentation updates in CI/CD workflows whenever API routes are modified.

**Comment by emvaldes** [comment]
### **Enhancing Developer-Friendliness**

#### **A. Interactive Features**
1. Enable **"Try It Out"** functionality in Swagger UI:
   - Add authentication headers or tokens to API requests in real time.
2. Include **auto-generated code snippets**:
   - Use Swagger plugins to provide SDK-like examples in Python, JavaScript, etc.

#### **B. Provide Usage Guides**
1. Add a **"Getting Started"** section in Swagger UI:
   - Explain authentication methods (API keys, OAuth2).
   - Provide environment setup instructions for developers.
2. Include **FAQs** and **Common Issues**:
   - Example: "What to do if the token expires?"

#### **C. Organize Endpoints**
1. Group endpoints by functionality:
   - Example: **User Management**, **Orders**, **Payments**.
2. Add tags and categories in the OpenAPI specification for better navigation.

---

### **4. Testing the Documentation**

#### **A. Validate Endpoints**
1. Use automated tests to verify that endpoints documented in Swagger match the actual API behavior.
2. Example with Postman:
   - Export OpenAPI spec to Postman and automate testing of all endpoints.

#### **B. User Feedback**
1. Share documentation with internal and external developers for usability testing.
2. Incorporate feedback into iterative improvements.

---

### **5. Deliverables**

1. **Interactive Swagger UI**: Hosted at `/api-docs` for developers and stakeholders.
2. **OpenAPI Specification**: Version-controlled and dynamically updated.
3. **Developer Guides**: Clear instructions for authentication, setup, and usage.
4. **Automation in CI/CD**: OpenAPI spec generation, validation, and deployment integrated into pipelines.

**Comment by emvaldes** [comment]
#### **B. Provide Usage Guides**
1. Add a **"Getting Started"** section in Swagger UI:
   - Explain authentication methods (API keys, OAuth2).
   - Provide environment setup instructions for developers.
2. Include **FAQs** and **Common Issues**:
   - Example: "What to do if the token expires?"

**Comment by emvaldes** [comment]
#### **C. Organize Endpoints**
1. Group endpoints by functionality:
   - Example: **User Management**, **Orders**, **Payments**.
2. Add tags and categories in the OpenAPI specification for better navigation.

**Comment by emvaldes** [comment]
### **Testing the Documentation**

#### **A. Validate Endpoints**
1. Use automated tests to verify that endpoints documented in Swagger match the actual API behavior.
2. Example with Postman:
   - Export OpenAPI spec to Postman and automate testing of all endpoints.

**Comment by emvaldes** [comment]
#### **B. User Feedback**
1. Share documentation with internal and external developers for usability testing.
2. Incorporate feedback into iterative improvements.

**Comment by emvaldes** [comment]
### **Deliverables**

1. **Interactive Swagger UI**: Hosted at `/api-docs` for developers and stakeholders.
2. **OpenAPI Specification**: Version-controlled and dynamically updated.
3. **Developer Guides**: Clear instructions for authentication, setup, and usage.
4. **Automation in CI/CD**: OpenAPI spec generation, validation, and deployment integrated into pipelines.

**Comment by emvaldes** [comment]
* Automating OpenAPI Documentation
* Using Custom Swagger Plugins
* Integrating Postman for API Testing

**Comment by emvaldes** [comment]
### **Automating OpenAPI Documentation Updates in CI/CD Pipelines**

Automating OpenAPI specification generation and validation ensures documentation is always up-to-date. Below is the complete setup process.

#### **A. Generating OpenAPI Specifications**

1. **Node.js Example with `swagger-autogen`**
   - Install the library:
     ```bash
     npm install swagger-autogen --save-dev
     ```

   - Create a `generate-swagger.js` file:
     ```javascript
     const swaggerAutogen = require('swagger-autogen')();

     const doc = {
       info: {
         title: 'API Documentation',
         description: 'API documentation generated automatically from code comments.',
       },
       host: 'localhost:3000',
       schemes: ['http'],
     };

     const outputFile = './swagger-output.json';
     const endpointsFiles = ['./routes/*.js'];

     swaggerAutogen(outputFile, endpointsFiles).then(() => {
       console.log('Swagger documentation generated successfully!');
     });
     ```

   - Add comments in your routes:
     ```javascript
     /**
      * @swagger
      * /users:
      *   get:
      *     summary: Retrieve a list of users.
      *     responses:
      *       200:
      *         description: A list of users.
      */
     app.get('/users', (req, res) => {
       res.send([{ id: 1, name: 'John' }]);
     });
     ```

   - Run the script to generate `swagger-output.json`:
     ```bash
     node generate-swagger.js
     ```

**Comment by emvaldes** [comment]
#### **B. Validating OpenAPI Specifications**

Use `swagger-cli` to validate OpenAPI specs during CI/CD.

1. Install `swagger-cli`:
   ```bash
   npm install -g swagger-cli
   ```

2. Validate the OpenAPI specification:
   ```bash
   swagger-cli validate swagger-output.json
   ```

3. Example GitHub Actions Workflow:
   ```yaml
   name: API Documentation CI

   on:
     pull_request:
       branches:
         - main

   jobs:
     generate-validate-docs:
       runs-on: ubuntu-latest

       steps:
         # Step 1: Checkout Code
         - name: Checkout code
           uses: actions/checkout@v3

         # Step 2: Install Dependencies
         - name: Install Node.js
           uses: actions/setup-node@v3
           with:
             node-version: '16'

         - name: Install Dependencies
           run: npm install

         # Step 3: Generate OpenAPI Spec
         - name: Generate OpenAPI Spec
           run: node generate-swagger.js

         # Step 4: Validate OpenAPI Spec
         - name: Validate OpenAPI Spec
           run: swagger-cli validate swagger-output.json

         # Step 5: Upload Spec as Artifact (Optional)
         - name: Upload OpenAPI Spec
           uses: actions/upload-artifact@v3
           with:
             name: openapi-spec
             path: ./swagger-output.json
   ```

**Comment by emvaldes** [comment]
#### **C. Publishing Documentation Automatically**
1. Use Swagger UI to serve the `swagger-output.json` file.
2. Deploy the documentation on a server or host it as a static site (e.g., GitHub Pages, S3).

**Comment by emvaldes** [comment]
### **Custom Swagger Plugins for Advanced Features**

Swagger plugins enhance the interactivity and usability of API documentation.

#### **A. Adding "Try It Out" with Authentication**
1. Enable "Try It Out" functionality in Swagger UI:
   - In Swagger UI setup:
     ```javascript
     const swaggerUi = require('swagger-ui-express');
     const swaggerDocument = require('./swagger-output.json');

     app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, {
       swaggerOptions: {
         authAction: {
           bearerAuth: {
             name: 'Authorization',
             schema: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
           },
         },
       },
     }));
     ```

2. Add headers for Bearer tokens in the OpenAPI spec:
   ```yaml
   components:
     securitySchemes:
       BearerAuth:
         type: http
         scheme: bearer
   security:
     - BearerAuth: []
   ```

**Comment by emvaldes** [comment]
#### **B. Auto-Generated Code Snippets**
1. Use Swagger UI plugins to display SDK-like examples:
   - Install Swagger UI plugins for code snippets:
     ```bash
     npm install swagger-codegen-cli --save
     ```

2. Add `x-codeSamples` in OpenAPI spec:
   ```yaml
   paths:
     /users:
       get:
         summary: Retrieve a list of users.
         responses:
           200:
             description: A list of users.
             content:
               application/json:
                 examples:
                   python:
                     value: |
                       import requests
                       response = requests.get('https://your-api-url.com/users')
                       print(response.json())
   ```

**Comment by emvaldes** [comment]
### **Integrating Postman for API Testing**

Postman can be integrated with Swagger/OpenAPI to test APIs interactively and automate endpoint validations.

#### **A. Export OpenAPI Spec to Postman**
1. Export OpenAPI spec (`swagger-output.json`) to Postman:
   - Go to **Postman > Import**.
   - Upload the OpenAPI spec.

2. Postman will auto-generate collections for all endpoints.

**Comment by emvaldes** [comment]
#### **B. Automate API Tests in Postman**
1. Create test cases for endpoints:
   - Example test in Postman:
     ```javascript
     pm.test("Status code is 200", function () {
       pm.response.to.have.status(200);
     });

     pm.test("Response time is below 500ms", function () {
       pm.expect(pm.response.responseTime).to.be.below(500);
     });
     ```

2. Export Postman collection as JSON.

3. Use Newman CLI to run tests in CI/CD:
   - Install Newman:
     ```bash
     npm install -g newman
     ```

   - Run Postman tests:
     ```bash
     newman run postman-collection.json
     ```

4. GitHub Actions Workflow for Newman:
   ```yaml
   name: API Test Workflow

   on:
     pull_request:
       branches:
         - main

   jobs:
     api-test:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Install Newman
           run: npm install -g newman

         - name: Run Postman Tests
           run: newman run postman-collection.json
   ```

**Comment by emvaldes** [comment]
### **Additional Enhancements**

#### **A. Using Power BI for Reporting**
1. Export API logs from Azure Monitor or OpenAPI validation logs.
2. Use Power BI to visualize metrics like:
   - Number of tested endpoints.
   - Pass/fail ratios.
   - Average response times.

**Comment by emvaldes** [comment]
#### **B. Developer-Focused Improvements**
1. Create "Quick Start" guides and FAQs in Swagger UI.
2. Add guides for SDK generation using Swagger Codegen or OpenAPI Generator.

**Comment by emvaldes** [comment]
### **CI/CD for Swagger/OpenAPI Integration**

Integrating Swagger/OpenAPI with CI/CD ensures your API documentation stays up-to-date, accurate, and automatically deployed with every code change. This guide explains how to set up a complete CI/CD pipeline for Swagger integration.

**Comment by emvaldes** [comment]
### **Steps for Setting Up CI/CD for Swagger/OpenAPI**

#### **Step 1: Automate OpenAPI Spec Generation**

Use tools like `swagger-autogen` (Node.js), `drf-yasg` (Python/Django), or `springdoc-openapi` (Java) to generate the OpenAPI spec during builds.

##### Example: Node.js with `swagger-autogen`
1. Create a script to generate OpenAPI specs from annotated code:
   ```javascript
   const swaggerAutogen = require('swagger-autogen')();

   const doc = {
     info: {
       title: 'API Documentation',
       description: 'Automatically generated Swagger/OpenAPI spec.',
     },
     host: 'localhost:3000',
     schemes: ['http'],
   };

   const outputFile = './swagger-output.json';
   const endpointsFiles = ['./routes/*.js']; // Path to route files

   swaggerAutogen(outputFile, endpointsFiles).then(() => {
     console.log('Swagger documentation generated successfully!');
   });
   ```

2. Add this script to your CI pipeline to regenerate the spec whenever the API code changes.

**Comment by emvaldes** [comment]
#### **Step 2: Validate OpenAPI Specification**

Use tools like `swagger-cli` to validate the generated OpenAPI spec for syntax correctness and completeness.

##### Example Validation Command:
```bash
swagger-cli validate swagger-output.json
```

##### GitHub Actions Step for Validation:
```yaml
- name: Validate OpenAPI Spec
  run: swagger-cli validate swagger-output.json
```

**Comment by emvaldes** [comment]
#### **Step 3: Host and Deploy Swagger UI**

##### **Option 1: Host Locally (e.g., Node.js)**
1. Install `swagger-ui-express` to serve Swagger UI:
   ```bash
   npm install swagger-ui-express
   ```

2. Use this code to serve Swagger UI:
   ```javascript
   const swaggerUi = require('swagger-ui-express');
   const swaggerDocument = require('./swagger-output.json');

   app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
   ```

3. Deploy the Node.js app using CI/CD to your staging/production environment.

##### **Option 2: Host as a Static Site (e.g., GitHub Pages or S3)**
1. Use Swagger UI to generate a static website for your documentation:
   - Download the Swagger UI distribution: https://github.com/swagger-api/swagger-ui
   - Replace the default `swagger.json` file in the `dist` folder with your `swagger-output.json`.

2. Deploy the `dist` folder to a static hosting service like:
   - **GitHub Pages**:
     ```bash
     git add dist
     git commit -m "Deploy Swagger UI"
     git push origin main
     ```
   - **Amazon S3**:
     ```bash
     aws s3 sync ./dist s3://your-bucket-name
     ```

**Comment by emvaldes** [comment]
#### **Step 4: Automate Documentation Updates in CI/CD**

##### **GitHub Actions Workflow Example**

Here’s a complete GitHub Actions workflow that generates, validates, and deploys Swagger documentation.

```yaml
name: Swagger Documentation CI/CD

on:
  push:
    branches:
      - main

jobs:
  generate-validate-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      # Step 3: Generate Swagger Documentation
      - name: Generate OpenAPI Spec
        run: node generate-swagger.js

      # Step 4: Validate OpenAPI Spec
      - name: Validate OpenAPI Spec
        run: swagger-cli validate swagger-output.json

      # Step 5: Deploy Documentation
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
```

**Comment by emvaldes** [comment]
#### **Step 5: Continuous Integration with Pull Requests**

Enable automated validation for pull requests to ensure API documentation remains accurate.

1. Validate OpenAPI spec for every PR:
   ```yaml
   name: Swagger Validation on PR

   on:
     pull_request:
       branches:
         - main

   jobs:
     validate-swagger:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Install Dependencies
           run: npm install

         - name: Generate OpenAPI Spec
           run: node generate-swagger.js

         - name: Validate OpenAPI Spec
           run: swagger-cli validate swagger-output.json
   ```

2. Add a status check for Swagger validation in GitHub:
   - Navigate to **Settings > Branch Protection Rules**.
   - Add `Swagger Validation on PR` as a required check.
