### ISSUE TITLE
DevSecOps : Public-facing Documentation (Swagger)

### ISSUE THREAD

**Issue by emvaldes** [CDCgov/prime-reportstream#17011]
The **"Public-facing Documentation initiative - OpenAPI documentation (Swagger)"** objective is closely related to the previously discussed sections on improving existing API documentation and setting up Swagger. However, if this initiative is specifically **public-facing**, additional considerations and strategies need to be implemented to ensure security, usability, and alignment with external developer needs.

#### **Objective:**
Create polished, secure, and interactive API documentation to be publicly accessible. This initiative aims to support external developers by offering easy-to-use, developer-friendly documentation while ensuring compliance with security and governance standards.

**Comment by emvaldes** [comment]
#### **1. Design and Usability for External Developers**

Public-facing documentation must cater to a broader audience, which might include developers with varying skill levels. Focus on:

1. **Clean and Intuitive Interface**:
   - Use Swagger UI for interactive and visually appealing documentation.
   - Include a "Getting Started" section to onboard new developers quickly.

2. **Comprehensive Information**:
   - Clearly describe all API endpoints, request/response formats, and error codes.
   - Provide examples for common use cases.

3. **Interactive Features**:
   - Enable "Try It Out" in Swagger UI for developers to test endpoints directly.
   - Offer downloadable SDKs or auto-generated code snippets for multiple programming languages (e.g., Python, JavaScript, Java).

---

#### **2. Security for Public APIs**

When exposing API documentation publicly, additional security measures must be in place:

1. **Authentication and Authorization**:
   - Ensure all API requests require proper authentication (e.g., API keys, OAuth2).
   - Add information about authentication in the documentation.

   Example OpenAPI Spec for OAuth2:
   ```yaml
   components:
     securitySchemes:
       OAuth2:
         type: oauth2
         flows:
           authorizationCode:
             authorizationUrl: https://example.com/oauth/authorize
             tokenUrl: https://example.com/oauth/token
             scopes:
               read: Read access
               write: Write access
   security:
     - OAuth2: [read, write]
   ```

2. **Rate Limiting and Throttling**:
   - Highlight rate limits in the documentation and provide error examples for rate-limiting scenarios.

   Example:
   ```yaml
   responses:
     429:
       description: Too Many Requests
       content:
         application/json:
           example:
             error: "Rate limit exceeded. Try again later."
   ```

3. **Mask Sensitive Information**:
   - Ensure no sensitive data, internal endpoints, or admin APIs are exposed in public documentation.

4. **Use of API Gateway**:
   - Host APIs behind a gateway (e.g., Azure API Management, AWS API Gateway) to control and monitor access.

---

#### **3. Hosting and Deployment of Public Documentation**

Public documentation must be highly available and user-friendly. Key considerations:

1. **Host as a Static Website**:
   - Use tools like Swagger UI or Redoc to generate static documentation and deploy it to:
     - GitHub Pages.
     - Amazon S3 with CloudFront for CDN.
     - Azure Static Web Apps.

2. **Add Custom Branding**:
   - Customize Swagger UI with your company’s logo, theme, and branding to ensure it aligns with the public-facing identity.

   Example for Custom Swagger UI Theme:
   ```javascript
   const swaggerUi = require('swagger-ui-express');
   const swaggerDocument = require('./swagger.json');

   app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, {
     customCss: '.swagger-ui .topbar { display: none }',
   }));
   ```

3. **Public URL**:
   - Ensure the documentation is accessible via a friendly and consistent URL (e.g., `https://docs.example.com` or `https://api.example.com/docs`).

4. **Search Engine Optimization (SEO)**:
   - Add metadata and descriptions for better search engine visibility.
   - Use tools like Algolia to provide a search bar for the documentation.

---

#### **4. Automation for Public-Facing Documentation**

1. **Integrate Documentation into CI/CD**:
   - Automatically generate and deploy updated documentation whenever API changes are merged into the main branch.
   - Use GitHub Actions, Jenkins, or other CI/CD tools for automated deployment.

   Example GitHub Actions Workflow for Deployment:
   ```yaml
   name: Deploy Public API Documentation

   on:
     push:
       branches:
         - main

   jobs:
     deploy-docs:
       runs-on: ubuntu-latest

       steps:
         # Step 1: Checkout Code
         - name: Checkout code
           uses: actions/checkout@v3

         # Step 2: Install Swagger Tools
         - name: Install Swagger UI
           run: npm install swagger-ui

         # Step 3: Generate Swagger Documentation
         - name: Generate Swagger Spec
           run: node generate-swagger.js

         # Step 4: Deploy to S3 or GitHub Pages
         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./dist
   ```

2. **Version Control for Documentation**:
   - Add versioning to the API documentation (e.g., `/v1/docs`, `/v2/docs`) to ensure developers can reference older versions as needed.

---

#### **5. Developer Support and Feedback Loop**

1. **Dedicated Feedback Section**:
   - Include a feedback mechanism in the documentation (e.g., a form or GitHub Issues link) for developers to report problems or request features.

2. **Community Engagement**:
   - Provide links to public forums, Slack, or Discord channels where developers can ask questions or collaborate.

3. **FAQs and Tutorials**:
   - Add a section for common questions and in-depth tutorials to help developers get started.

---

### **Deliverables**

1. **Polished Public-Facing Documentation**:
   - Accessible via a custom public URL with branding.
   - Fully interactive (e.g., "Try It Out" enabled).

2. **Security Measures**:
   - Documentation reflects proper authentication, authorization, and rate-limiting strategies.

3. **Automated Updates**:
   - CI/CD pipeline ensures documentation is always current and accurately reflects the latest API changes.

4. **Developer Resources**:
   - Code snippets, SDKs, FAQs, and tutorials.

---

### **Integration With Existing Sections**

- This section complements the **Improve Existing API Documentation with Swagger** initiative by focusing on external users' needs.
- Works in parallel with the **Adopt and Deploy Load Testing Framework** to ensure developers can test APIs using public-facing documentation.

**Comment by emvaldes** [comment]
#### **Security for Public APIs**

When exposing API documentation publicly, additional security measures must be in place:

1. **Authentication and Authorization**:
   - Ensure all API requests require proper authentication (e.g., API keys, OAuth2).
   - Add information about authentication in the documentation.

   Example OpenAPI Spec for OAuth2:
   ```yaml
   components:
     securitySchemes:
       OAuth2:
         type: oauth2
         flows:
           authorizationCode:
             authorizationUrl: https://example.com/oauth/authorize
             tokenUrl: https://example.com/oauth/token
             scopes:
               read: Read access
               write: Write access
   security:
     - OAuth2: [read, write]
   ```

2. **Rate Limiting and Throttling**:
   - Highlight rate limits in the documentation and provide error examples for rate-limiting scenarios.

   Example:
   ```yaml
   responses:
     429:
       description: Too Many Requests
       content:
         application/json:
           example:
             error: "Rate limit exceeded. Try again later."
   ```

3. **Mask Sensitive Information**:
   - Ensure no sensitive data, internal endpoints, or admin APIs are exposed in public documentation.

4. **Use of API Gateway**:
   - Host APIs behind a gateway (e.g., Azure API Management, AWS API Gateway) to control and monitor access.

**Comment by emvaldes** [comment]
#### **Hosting and Deployment of Public Documentation**

Public documentation must be highly available and user-friendly. Key considerations:

1. **Host as a Static Website**:
   - Use tools like Swagger UI or Redoc to generate static documentation and deploy it to:
     - GitHub Pages.
     - Amazon S3 with CloudFront for CDN.
     - Azure Static Web Apps.

2. **Add Custom Branding**:
   - Customize Swagger UI with your company’s logo, theme, and branding to ensure it aligns with the public-facing identity.

   Example for Custom Swagger UI Theme:
   ```javascript
   const swaggerUi = require('swagger-ui-express');
   const swaggerDocument = require('./swagger.json');

   app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, {
     customCss: '.swagger-ui .topbar { display: none }',
   }));
   ```

3. **Public URL**:
   - Ensure the documentation is accessible via a friendly and consistent URL (e.g., `https://docs.example.com` or `https://api.example.com/docs`).

4. **Search Engine Optimization (SEO)**:
   - Add metadata and descriptions for better search engine visibility.
   - Use tools like Algolia to provide a search bar for the documentation.

**Comment by emvaldes** [comment]
#### **Automation for Public-Facing Documentation**

1. **Integrate Documentation into CI/CD**:
   - Automatically generate and deploy updated documentation whenever API changes are merged into the main branch.
   - Use GitHub Actions, Jenkins, or other CI/CD tools for automated deployment.

   Example GitHub Actions Workflow for Deployment:
   ```yaml
   name: Deploy Public API Documentation

   on:
     push:
       branches:
         - main

   jobs:
     deploy-docs:
       runs-on: ubuntu-latest

       steps:
         # Step 1: Checkout Code
         - name: Checkout code
           uses: actions/checkout@v3

         # Step 2: Install Swagger Tools
         - name: Install Swagger UI
           run: npm install swagger-ui

         # Step 3: Generate Swagger Documentation
         - name: Generate Swagger Spec
           run: node generate-swagger.js

         # Step 4: Deploy to S3 or GitHub Pages
         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./dist
   ```

2. **Version Control for Documentation**:
   - Add versioning to the API documentation (e.g., `/v1/docs`, `/v2/docs`) to ensure developers can reference older versions as needed.
