### ISSUE TITLE
An a ReportStream Ops person, I want my yamlito filter syntax to be consistent

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#3309]
This is follow-on work to #1244, in which Organizaton-level filters were added with a syntax like this:

```
filters:
  - topic: "covid-19"
    jurisdictionalFilter:  [ "foo()" ]
    qualityFilter:  [ "bar()", "baz()" ] 
    routingFilters: [ "quux()" ]

```
Note that filters is a list, because an Organization may handle multiple `topic`.

I did not change the Organization level filtering syntax, because it would have involved fixing about 100 receivers syntax in production, which will require great care.   There is also one difference:  a Receiver only takes one topic, so the filters does not need to be a list.

So the job is to change the current yaml language for individual receivers from: 

```
- jurisdictionalFilter:  [ "foo()" ]
- qualityFilter: [ "bar()" ]
- routingFilter:  [ "baz()" ]
```

To match the newer syntax in use for Organizations:

```
  - filters:
    jurisdictionalFilter:  [ "foo()" ]
    qualityFilter: [ "bar()" ]
    routingFilter:  [ "baz()" ]
```
(Note the topic: is not needed for receivers.  Note that its not a list)

If this seems like way too much work for little payoff, then delete this ticket.
