### ISSUE TITLE
Deleted directories referenced in dependabot.yml

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#5115]
`/frontend` doesn't exist anymore. Seems like dependabot should be complaining? 

Anyways, we should probably clean up `prime-reportstream/.github/dependabot.yml` and remove references to `/frontend` [Ref](https://github.com/CDCgov/prime-reportstream/blob/master/.github/dependabot.yml#L16)

```yml
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
 ```
