### ISSUE TITLE
Add quality checks to Terraform pipeline

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#5520]
As a devops engineer I would like my Terraform changes to be validated against best practices. For instance I should not be permitted to add untagged resources. To do this I would like to add [Chekov](https://github.com/bridgecrewio/checkov-action) to our Terraform pipeline.

This should run on opening a PR
This should look at only /operations/app/terraform

```
on:
  pull_request:
    paths: 
       - '/operations/app/terraform'
```
