### ISSUE TITLE
Simplify the generation of OIDs in HL7 to FHIR translation config

### ISSUE THREAD

**Issue by carlosfelix2** [CDCgov/prime-reportstream#5918]
### User Story:
As a developer, I want to simplify the generation of OIDs in the HL7 to FHIR translation configuration, so that the configuration is less complicated.

### Description/Use Case
The configuration for the HL7 to FHIR translation library is a bit limited and string concatenation requires some workarounds that make the configuration a bit harder to follow.  It will be nice to have a simple way to generate these OID URLs.  For example, data may have an OID of `2.1.1.2.4.56.64.3.3` and we need to convert that to `urn:oid:2.1.1.2.4.56.64.3.3`. 

### Risks/Impacts/Considerations
* The library may not easily allow a simplification.

### Dev Notes:
* Example: See `prime-router/metadata/fhir_mapping/hl7/extension/ExtensionMeta.yml`, `extension_4` property
* The Linux4Health library can be extended with Java utilities that can be used in the configuration.  There are several examples of this in the configuration already.  Can we add a new one?  Or better yet, does one already exist?

### Acceptance Criteria
* Simplify the generation of OID URLs if possible.
* If the simplification can be made then update all instances in the configuration where the URL concatenation is being done.

**Comment by PatriciaPerozoUSDS** [comment]
After talking to Carlos, we've decided further simplification is not possible. 

**Important context** - There are two ways to use JEXL in the linux4health mapping files.
1. By officially using the expressionType: JEXL option. For shorthand through out the rest of the explanation, I will call this `Explicit JEXL`. Fake example below:
```
text:
    type: STRING
    valueOf: 'String.format("%s %s %s %s %s", prefix, first, middle, family, suffix)'
    expressionType: JEXL
    vars:
      prefix: String, XPN.5 |XCN.6 |CNN.6 |NDL.6 | PPN.6
      first: String, XPN.2 |XCN.3 |CNN.3 |NDL.3 | PPN.3
      middle: String, XPN.3 |XCN.4 |CNN.4 |NDL.4 | PPN.4
      family: String, XPN.1 |XCN.2 |CNN.2 |NDL.2 | PPN.2
      suffix: String, XPN.4 |XCN.5 |CNN.5 |NDL.5 | PPN.5
```
2. By taking on a JEXL expression after a variable definition. For shorthand through out the rest of the explanation, I will call this `Implied JEXL`. Real Example from code base:
```
length:
    valueOf: datatype/Duration
    expressionType: resource
    vars: 
      pv2time: STRING, PV2.11
      pv1length: PV1, GeneralUtils.pv1DurationLength(pv1length,ZONEID)
```
All 4 utils classes work while using `Explicit JEXL`.  Unfortunately it seems only the `GeneralUtils` class is accessible using the `Implicit JEXL`.

**What does this mean?**
- We can only use JEXL expressions on fields that can have type string.
- That means extensions can't use JEXL expressions outside of General Utils classes used through Implicit JEXL
