### ISSUE TITLE
API documentation issues list

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6243]
While trying to use the OpenAPI docs to generate automated client-side tests, noticed lots of issues and inconsistencies. This list is just documenting potential issues so they don't get lost.

Note: "files" refers to the yml OpenAPI doc files found in `prime-router/docs/api`

- [ ] `info:  title:` for files are not all unique many are copy/pasted duplicates (e.g. `"Prime ReportStream"`).
     The format seems like it should be `ResportStream [File Name] API` 
     For example, `./covid-result-metadata.yml` is `"ReportStream COVID Result Metadata API"`

- [ ] Filenames are not consistent. 
    Only offender seems to be `lookup-tables-openapi.yaml` it should probably be `lookup-tables-management.yaml` based on the `info:  title`

- [ ] `info:  description`is missing from many files

- [ ] `info:  version` is inconsistent across files. What is correct? 
  - `admin.yml`, `reports.yml` has `version: 0.2.0-oas3` 
  - check.yml, etc has `version: "0.1"`
  - others have `version: "1.0"`
- [ ] `info:  license` is missing from most files. It appears in `waters-delivery.yml`
```yml
  license:
    name: Creative Commons Zero v1.0 Universal
    url: https://github.com/CDCgov/prime-reportstream/blob/master/LICENSE
```

- [ ] Top level `servers` missing from all files except `waters-delivery.yml`

```yml
servers:
  - url: https://prime.cdc.gov/api
    description: Production server (uses live data)
  - url: http://localhost:7071/api
    description: Developer Environment
```

- [ ] `responses:` often are missing failure codes and ONLY have 200

```yml
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: resource does not exist
```
Should also consider adding/using:
 - `404`'s `resource` is name of the type of resource like "organization" or "report"
 - `413 Payload Too Large` when Sender tries to upload data that's too big
 - `422 Unprocessable Entity` for when the response would be too large (e.g. requested too big of date range)

- [ ] `check.yml` is missing required parameters

- [ ] `components:  securitySchemes:` is inconsistent:

```yml
components:
  securitySchemes:
    OAuth2:
      $ref: 'https://raw.githubusercontent.com/CDCgov/prime-reportstream/master/prime-router/docs/api/components/security_schemes.yml#/OAuth2'
```

> The security_schemes.yml:
    
```yml
OAuth2:
  type: oauth2
  flows:
    authorizationCode:
      authorizationUrl: https://hhs-prime.okta.com/oauth/authorize
      tokenUrl: https://hhs-prime.okta.com/oauth/token
      scopes:
        user: Grants read access
        org_admin: Grants write access to single org
        system_admin: Grants access to admin operations
Server2Server: # aka two-legged aka fhirauth
  type: http
  scheme: bearer
  bearerFormat: JWT
ApiKeyAuth:
  type: apiKey
  in: header
  name: x-functions-key
```

> The file [docs/proposals/0004-settings-api/openapi.yml](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0004-settings-api/openapi.yml) says it should look more like this?

```yml
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-functions-key
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://hhs-prime.okta.com/oauth/authorize
          tokenUrl: https://hhs-prime.okta.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
```

 - [ ] Generic API issue: many queries are missing "TOP N" to set an upper limit on the amount of memory/data they can consume.
 
 - [ ] Fix top-level description "This is a stub to be completed when this API is reviewed" in several files: email-sender.yml, covid-result-metadata.yml, email-engine.yml, metadata.yml
