### ISSUE TITLE
The `./prime sender reqtoken` call looks for orgs in the local organization.yml file, instead of doing a proper API call to ReportStream to find the org.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#7707]
### **Describe the bug**
The `./prime sender reqtoken` call looks for orgs in the local organization.yml file, instead of doing a proper API call to ReportStream to find the org.

**Impact**
If we create a new org/sender and then immediately try to experiement with creating an access token, it won't work.    Hack workaround is to add the org/sender to your settings/organization.yml, but you should not have to do that.

### **To Reproduce**

Create a new org and sender:

```
- name: foo
  description: Test Sender
  jurisdiction: FEDERAL
  senders:
    - name: default
      organizationName: foo
      topic: covid-19
      customerStatus: active
      schemaName: primedatainput/pdi-covid-19
      format: CSV
```

Then submit it to your local RS:

```
./prime multiple-settings set --input ./junk/foo.yml
```

Then call 
```
./prime sender reqtoken --private-key doesnt-matter --scope "whatever" --name unhealthy.default
```

The call requires a keypair, so generate one:

```
openssl genrsa -out my-rsa-keypair.pem 2048
openssl rsa -in my-rsa-keypair.pem -outform PEM -pubout -out my-rsa-public-key.pem
```

This call will fail with an  error
./prime sender reqtoken --private-key my-rsa-keypair.pem --scope "whatever" --name foo.default

THIS IS THE BUG:

**Unable to find sender full name (organization.sender) foo.default**

### **Expected behavior**

Instead, that call should find the org/sender by querying the locally running API.
