### ISSUE TITLE
bug: end2end_up smoke test fails if full-elr data is routed to more than one receiver.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#8294]
## Describe the bug
The end2end_up test, line 141 in BasicTests.kt, assumes that the report will be routed to only one receiver.

The smoke test should work even with arbitrarily complex settings data.   Someone (like me) might have local or staging settings set up to route full-elr data to other receivers.    

The query should be changed only look for the report going to the `ignore.FULL_ELR` receiver, and ignore the others.   The query used in the old smoke test is an example of this.

## Impact on ReportStream
- The smoke tests fail.

## Steps to reproduce
1. Run ReportStream
2. Add a new receiver (below) that will route all data:   `./prime receiver set --input ./bug-example.yml`

```
name: bug-example
externalName: bug-example
organizationName: ignore
topic: full-elr
customerStatus: active
jurisdictionalFilter:
  - true
timing:
  operation: MERGE
  numberPerDay: 1440 # Every minute
  initialTime: 00:00
translation: !<HL7>
  schemaName: "metadata/hl7_mapping/STLTs/CO/CO"
  useTestProcessingMode: false
  useBatchHeaders: true
  type: "HL7"
  receivingApplicationName: "CO-ELR"
  receivingFacilityName: "CO"
transport:
  type: SFTP
  host: sftp
  port: 22
  filePath: ./upload
  credentialName: DEFAULT-SFTP
```

3. Run ./prime test --run end2end_up
4. You'll get the exception pasted below.

## Expected behavior
The test passes regardless of what unrelated data is in settings.
