### ISSUE TITLE
Add Sender Configuration to Senders

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#843]
In order to allow for a sender to have hard-coded values that get added into the `Report` object on ingestion. 

Two examples are:

- Having a `processing_mode_code` set for senders who are still building
- Manually setting a CLIA or a lab name for a sender who has a schema that doesn't include it

We should add a Sender Configuration object on senders, in the same fashion we have `TranslationConfiguration` for outbound translations. It could potentially even inherit from `TranslationConfiguration`.

**Comment by MauriceReeves-usds** [comment]
Moving to `In Progress` to start working on this.

**Comment by jimduff-usds** [comment]
I used the field default feature as a workaround for the absence of this feature.  It is ok, but not perfect.   The main problem is that flipping a sender from "T" Training mode in production to "P" production mode in production currently requires a code release since its in the .schema, not in the settings.

Here's an example of how I do this for a Sender called MoHealth:

```
---
name: mohealth-covid-19
description: Every Day we provide Mo and Mo Health
topic: covid-19
trackingElement: specimen_id
basedOn: covid-19
extends: direct/direct-covid-19

elements:
  - name: sender_id
    default: MoHealth

  - name: processing_mode_code
    default: T

```
