### ISSUE TITLE
Automate reverting deploys

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#9117]
As a devops engineer (or anyone else involved in deploys) I want a quick way to undo deploying a container.

This should be relatively easy - ideally we'd only need to run a couple Azure CLI commands. 
1. Get the UID for the container (most recent -1)
2. Deploy that container to the candidate slot
3. Swap to it

**Comment by lucasdze** [comment]
GitHub Action workflow that resets a prod branch back to its status from 2 days ago

```
name: Reset Branch

on:
  workflow_dispatch:

jobs:
  reset-branch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Reset Branch
      run: |
        # Set the branch name you want to reset
        BRANCH_NAME="your-branch-name"
        
        # Calculate the date from 2 days ago in ISO 8601 format
        TWO_DAYS_AGO=$(date --iso-8601=seconds -d '2 days ago')
        
        # Fetch the commit hash from 2 days ago on the branch
        COMMIT_HASH=$(git log --before="$TWO_DAYS_AGO" --format="%H" -n 1 $BRANCH_NAME)
        
        # Reset the branch to the commit hash
        git reset --hard $COMMIT_HASH
        
        # Force push the reset branch
        git push --force origin $BRANCH_NAME

```
